const adminUi = { token:'', generation:0, revision:0, tab:'overview', overview:null, list:null, detail:null, busy:false, error:'', filters:{query:'',access:'all',plan:'all',connection:'all',sync:'all',offset:0} };
function adminAllowed() { return Boolean(authState.token && authState.user?.telegramUserId === '5062414502'); }
function adminReset() {
  adminUi.revision++; Object.assign(adminUi,{token:'',generation:0,overview:null,list:null,detail:null,busy:false,error:'',tab:'overview',filters:{query:'',access:'all',plan:'all',connection:'all',sync:'all',offset:0}});
  const root=document.querySelector('[data-admin-root]'); if(root)root.innerHTML='';
  document.querySelectorAll('[data-admin-nav]').forEach(n=>n.hidden=true);
}
function adminAccess() {
  document.querySelectorAll('[data-admin-nav]').forEach(n=>n.hidden=!adminAllowed());
  if(!adminAllowed()) { adminReset(); if(location.hash==='#admin')setView('dashboard'); }
}
const adminPlanName = id => ({start:'Старт',growth:'Рост',pro:'Профи',maximum:'Максимум',pro_demo:'Демо'})[id] || id || 'Без тарифа';
const adminLabel = value => ({connected_read_only:'Подключён',not_connected:'Не подключён',attention:'Требует внимания',blocked:'Остановлен',ok:'В порядке',partial:'Ошибка отдельного плагина',retrying:'Повторная попытка',not_observed:'Нет данных',disabled:'Отключена'})[value] || value || '—';
const adminPluginName = id => state.plugins.find(p=>p.id===id)?.name || ({'zetslay.stars-relay':'Stars Relay','zetslay.kosell-rent':'Kosell Rent','zetslay.confirm-reminder':'Confirm Reminder','zetslay.review-reminder':'Review Reminder','zetslay.sales-pause':'Пауза продаж','zetslay.mass-price-editor':'Mass Price Editor','zetslay.lot-cloner':'Lot Cloner','zetslay.auto-review-bonus':'Auto Review Bonus','zetslay.tiktok-lzt-market':'TikTok LZT Market'})[id] || id;
function adminDate(value) { return value && Number.isFinite(new Date(value).getTime()) ? new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Moscow'}).format(new Date(value)) : '—'; }
function adminTag(label,tone='muted') { return `<span class="admin-tag admin-tag--${tone}">${escapeHtml(label)}</span>`; }
function adminTabLabel(tab) { return ({overview:'Обзор',users:'Пользователи',attention:'Проблемы'})[tab] || 'Обзор'; }
function adminMetric(label,value,note,key='') { return `<button type="button" class="admin-metric" ${key?`data-admin-metric="${key}"`:''}><span>${label}</span><strong>${escapeHtml(value ?? '—')}</strong><small>${note}</small></button>`; }
function adminOverviewMarkup(d) {
  const max=Math.max(1,...d.registrations.map(r=>r.count));
  return `<div class="admin-metrics">${adminMetric('Пользователи',d.users,'Всего зарегистрировано','users')}${adminMetric('Новые за 7 дней',d.newUsers,'Регистрации за последнюю неделю','new')}${adminMetric('Активный доступ',d.activePlans,'Состояние тарифа в базе','active')}${adminMetric('Магазины',d.connectedStores,'Подключение сохранено','connected')}${adminMetric('Требуют внимания',d.attentionUsers,'Подключение или синхронизация','attention')}</div>
  <div class="admin-overview-grid"><section class="admin-card"><header><div><h2>Регистрации</h2><p>Последние 14 дней · время Москвы</p></div><span class="admin-pill">${d.newUsers} за неделю</span></header><div class="admin-chart" role="img" aria-label="Регистрации пользователей за 14 дней">${d.registrations.map(r=>`<div title="${escapeHtml(r.day)}: ${r.count}"><span>${r.count}</span><i style="height:${Math.max(2,r.count/max*110)}px"></i><small>${escapeHtml(r.day.slice(8))}</small></div>`).join('')}</div></section>
  <section class="admin-card"><header><div><h2>Тарифы и доступ</h2><p>Действующие записи кабинетов</p></div></header><div class="admin-plan-list">${d.plans.map(p=>`<div><span>${escapeHtml(adminPlanName(p.id))} ${adminTag(p.active?'Активен':'Неактивен',p.active?'green':'muted')}</span><strong>${p.count}</strong></div>`).join('')||'<p>Пользователей пока нет</p>'}</div><p class="admin-note">Оплата ещё не подключена. Эти числа отражают доступ к сервису, а не оплаченные подписки или выручку.</p></section>
  <section class="admin-card"><header><div><h2>Использование плагинов</h2><p>Установлено / включено</p></div></header><div class="admin-plan-list">${d.plugins.map(p=>`<div><span>${escapeHtml(adminPluginName(p.id))}</span><strong>${p.installed} <small>/ ${p.enabled}</small></strong></div>`).join('')||'<p>Установленных плагинов пока нет</p>'}</div></section>
  <section class="admin-card admin-health-card"><header><div><h2>Контроль сервиса</h2><p>Что требует вашей проверки</p></div></header><button type="button" data-admin-metric="attention"><span>Проблемы подключения и синхронизации</span><strong>${d.attentionUsers}</strong><b>→</b></button><div><span>Открытые обращения пользователей</span><strong>${d.openRequests}</strong></div><p class="admin-note">Обращения доступны в существующем разделе юридических запросов. Панель показывает сохранённое состояние и не запускает действия в магазинах.</p><span class="admin-observed">Снимок: ${adminDate(d.observedAt)}</span></section></div>`;
}
function adminFiltersMarkup() {
  const f=adminUi.filters,select=(key,label,options)=>`<label>${label}<select name="${key}">${options.map(([value,name])=>`<option value="${value}" ${f[key]===value?'selected':''}>${name}</option>`).join('')}</select></label>`;
  return `<form class="admin-filters" data-admin-search><label class="admin-search">Поиск<input name="query" maxlength="100" value="${escapeHtml(f.query)}" placeholder="Email, Telegram ID, пользователь или магазин"></label>${select('access','Доступ',[['all','Любой'],['active','Активный'],['inactive','Неактивный']])}${select('plan','Тариф',[['all','Все тарифы'],['start','Старт'],['growth','Рост'],['pro','Профи'],['maximum','Максимум'],['pro_demo','Демо'],['none','Без тарифа'],['other','Другой']])}${select('connection','Магазин',[['all','Все'],['connected','Подключён'],['missing','Не подключён'],['attention','Требует внимания']])}${select('sync','Синхронизация',[['all','Любая'],['ok','В порядке'],['problem','Ошибки'],['unknown','Нет наблюдений']])}<button type="submit" class="button button--primary" ${adminUi.busy?'disabled':''}>Найти</button><button type="button" class="button button--ghost" data-admin-clear>Сбросить</button></form>`;
}
function adminTableMarkup(list) {
  return `<section class="admin-card admin-users-card"><header><div><h2>Пользователи <span>${list.total}</span></h2><p>Нажмите на пользователя, чтобы открыть карточку</p></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Пользователь</th><th>Тариф</th><th>Магазин FunPay</th><th>Синхронизация</th><th>Плагины</th><th>Регистрация</th></tr></thead><tbody>${list.users.map(u=>`<tr><td><button type="button" class="admin-user-link" data-admin-user="${escapeHtml(u.id)}"><span class="admin-user-avatar">${escapeHtml((u.displayName||u.email||'TG').slice(0,2).toUpperCase())}</span><span><strong>${escapeHtml(u.displayName||u.email||'Telegram-аккаунт')}</strong><small>${escapeHtml(u.telegramUserId?'TG '+u.telegramUserId:u.email||u.id)}</small></span></button></td><td><strong>${escapeHtml(adminPlanName(u.workspace.plan.id))}</strong>${adminTag(u.workspace.plan.active?'Активен':'Неактивен',u.workspace.plan.active?'green':'muted')}</td><td><strong>${escapeHtml(u.store?.name||'Не подключён')}</strong><small>${escapeHtml(u.store?.id?'ID '+u.store.id:adminLabel(u.connectionStatus))}</small></td><td>${adminTag(adminLabel(u.sync.status),u.sync.status==='ok'?'green':['blocked','retrying','partial'].includes(u.sync.status)?'amber':'muted')}<small>${escapeHtml(u.sync.code||adminDate(u.sync.lastSuccessAt))}</small></td><td><strong>${u.enabledPlugins} <small>/ ${u.installedPlugins}</small></strong></td><td>${adminDate(u.createdAt)}</td></tr>`).join('')||'<tr><td colspan="6"><div class="admin-empty">Пользователи не найдены. Попробуйте изменить фильтры.</div></td></tr>'}</tbody></table></div><footer class="admin-pagination"><span>${list.total?list.offset+1:0}–${Math.min(list.offset+list.users.length,list.total)} из ${list.total}</span><div><button type="button" class="button button--ghost" data-admin-page="${Math.max(0,list.offset-25)}" ${list.offset===0||adminUi.busy?'disabled':''}>Назад</button><button type="button" class="button button--ghost" data-admin-page="${list.nextOffset??0}" ${list.nextOffset===null||adminUi.busy?'disabled':''}>Далее</button></div></footer></section>`;
}
function adminDetailMarkup(d) {
  const u=d.user,field=(label,value)=>`<div><dt>${label}</dt><dd>${escapeHtml(value??'—')}</dd></div>`;
  return `<section class="admin-detail" aria-label="Карточка пользователя"><header><div><span class="admin-eyebrow">Карточка пользователя</span><h2>${escapeHtml(u.displayName||u.email||'Telegram-аккаунт')}</h2><p>${escapeHtml(u.id)}</p></div><button type="button" class="button button--ghost" data-admin-close>Закрыть карточку</button></header><div class="admin-detail-grid"><section class="admin-card"><h3>Аккаунт</h3><dl>${field('Email',u.email)}${field('Telegram ID',u.telegramUserId)}${field('Регистрация',adminDate(u.createdAt))}${field('Последний вход',adminDate(u.lastLoginAt))}${field('2FA',u.mfaEnabled?'Включена':'Выключена')}${field('ID кабинета',u.workspace.id)}${field('Личный бот',u.botUsername?'@'+u.botUsername:'Не подключён')}</dl></section><section class="admin-card"><h3>Подписка и магазин</h3><dl>${field('Тариф',adminPlanName(u.workspace.plan.id))}${field('Доступ',u.workspace.plan.active?'Активный':'Неактивный')}${field('Дата активации',adminDate(u.workspace.plan.activatedAt))}${field('Окончание подписки','Срок пока не учитывается')}${field('Магазин',u.store?.name)}${field('ID FunPay',u.store?.id)}${field('Подключение',adminLabel(u.connectionStatus))}${field('Прокси',u.store?.proxyConfigured?'Настроен':'Нет данных')}</dl></section><section class="admin-card"><h3>Синхронизация</h3><dl>${field('Состояние',adminLabel(u.sync.status))}${field('Последний успех',adminDate(u.sync.lastSuccessAt))}${field('Последний сбой',adminDate(u.sync.lastFailureAt))}${field('Следующая попытка',adminDate(u.sync.nextAttemptAt))}${field('Код ошибки',u.sync.code)}${field('Последовательных сбоев',u.sync.failures)}</dl></section><section class="admin-card"><h3>Плагины · ${d.plugins.length}</h3><div class="admin-plan-list">${d.plugins.map(p=>`<div><span>${escapeHtml(adminPluginName(p.id))}</span>${adminTag(p.enabled?'Включён':'Выключен',p.enabled?'green':'muted')}</div>`).join('')||'<p>Плагины не установлены</p>'}</div></section></div><section class="admin-card"><h3>Последние события аккаунта</h3><ol class="admin-events">${d.events.map(e=>`<li><span>${escapeHtml(e.event)}</span><time>${adminDate(e.at)}</time></li>`).join('')||'<li>Событий пока нет</li>'}</ol></section></section>`;
}
function renderAdminPanel() {
  const root=document.querySelector('[data-admin-root]'); if(!root)return;
  if(!adminAllowed()){root.innerHTML='<div class="admin-empty">Доступ только для владельца сервиса.</div>';return;}
  root.innerHTML=`<header class="admin-heading"><div><span class="admin-eyebrow">Управление ZetSlay</span><h1>Админ-панель</h1><p>Пользователи, доступ и работоспособность кабинетов.</p></div><button type="button" class="button button--ghost" data-admin-refresh ${adminUi.busy?'disabled':''}>${adminUi.busy?'Загружаем…':'Обновить данные'}</button></header><nav class="admin-tabs" aria-label="Разделы админ-панели">${['overview','users','attention'].map(t=>`<button type="button" data-admin-tab="${t}" aria-current="${adminUi.tab===t?'page':'false'}">${adminTabLabel(t)}</button>`).join('')}</nav>${adminUi.error?`<p class="admin-error" role="alert">${escapeHtml(adminUi.error)}</p>`:''}${adminUi.busy?'<p class="admin-loading" role="status">Загружаем актуальные данные…</p>':''}${adminUi.detail?adminDetailMarkup(adminUi.detail):adminUi.tab==='overview'?(adminUi.overview?adminOverviewMarkup(adminUi.overview):'<div class="admin-empty">Сводка ещё не загружена</div>'):adminFiltersMarkup()+(adminUi.list?adminTableMarkup(adminUi.list):'<div class="admin-empty">Список ещё не загружен</div>')}`;
}
async function adminLoad(kind='all',id='') {
  if(!adminAllowed()){adminAccess();return;}
  if(kind==='all' && adminUi.detail){kind='detail';id=adminUi.detail.user.id;}
  const token=authState.token,generation=sessionGeneration,revision=++adminUi.revision;
  const current=()=>adminAllowed()&&token===authState.token&&generation===sessionGeneration&&revision===adminUi.revision;
  adminUi.token=token;adminUi.generation=generation;adminUi.busy=true;adminUi.error='';renderAdminPanel();
  try {
    if(kind==='detail') {const detail=await apiRequest('/api/v1/admin/users/'+encodeURIComponent(id),{authenticated:true});if(current())adminUi.detail=detail;}
    else if(adminUi.tab==='overview') {const data=await apiRequest('/api/v1/admin/overview',{authenticated:true});if(current())adminUi.overview=data;}
    else { const filters={...adminUi.filters};
      if(adminUi.tab==='attention') {filters.attention='needed';}
      const data=await apiRequest('/api/v1/admin/users?'+new URLSearchParams(filters),{authenticated:true});if(current()){adminUi.list=data;adminUi.detail=null;}
    }
  } catch(e) {if(current()){if(e.code==='ACCESS_DENIED'||e.code==='INVALID_SESSION'){adminUi.overview=null;adminUi.list=null;adminUi.detail=null;}adminUi.error=humanError(e);}}
  finally {if(current()){adminUi.busy=false;renderAdminPanel();}}
}
function adminRoute(view) { if(view!=='admin')return;adminAccess();if(adminAllowed())adminLoad(); }
document.addEventListener('submit',event=>{
  const form=event.target.closest('[data-admin-search]');if(!form)return;event.preventDefault();if(!adminAllowed())return;
  const f=Object.fromEntries(new FormData(form));adminUi.filters={...f,offset:0};adminLoad();
});
document.addEventListener('click',event=>{
  const b=event.target.closest('[data-admin-tab],[data-admin-refresh],[data-admin-user],[data-admin-close],[data-admin-page],[data-admin-clear],[data-admin-metric]');if(!b||!adminAllowed()||b.disabled)return;
  if(b.hasAttribute('data-admin-user')){adminLoad('detail',b.dataset.adminUser);return;}
  if(b.hasAttribute('data-admin-close')){adminUi.revision++;adminUi.busy=false;adminUi.detail=null;renderAdminPanel();return;}
  if(b.hasAttribute('data-admin-tab')){adminUi.tab=b.dataset.adminTab;adminUi.detail=null;adminUi.list=null;adminUi.filters.offset=0;}
  if(b.hasAttribute('data-admin-page'))adminUi.filters.offset=Number(b.dataset.adminPage);
  if(b.hasAttribute('data-admin-clear')){adminUi.filters={query:'',access:'all',plan:'all',connection:'all',sync:'all',offset:0};adminUi.tab='users';}
  if(b.hasAttribute('data-admin-metric')){adminUi.tab=b.dataset.adminMetric==='attention'?'attention':'users';adminUi.detail=null;adminUi.filters={query:'',access:b.dataset.adminMetric==='active'?'active':'all',connection:b.dataset.adminMetric==='connected'?'connected':'all',plan:'all',sync:'all',registered:b.dataset.adminMetric==='new'?'week':'all',offset:0};}
  adminLoad();
});
