/* Guides describe the shipped cabinet; reading never starts automation or requests secrets. */
const KB_CATEGORIES = Object.freeze([
  {id:'connection',name:'Подключение',icon:'shield',color:'blue'},
  {id:'store',name:'Работа с магазином',icon:'bag',color:'green'},
  {id:'plugins',name:'Плагины',icon:'puzzle',color:'purple'},
  {id:'kosell',name:'Kosell Rent',icon:'bolt',color:'amber'},
  {id:'account',name:'Аккаунт и тарифы',icon:'user',color:'blue'},
  {id:'diagnostics',name:'Решение проблем',icon:'help',color:'rose'}
]);
const kbSection = (title,body,extra={}) => ({title,body:Array.isArray(body)?body:[body],...extra});
const KB_ARTICLES = Object.freeze([
 {id:'connect',category:'connection',title:'Подключить магазин с нуля',summary:'Telegram-бот, Golden Key, прокси и проверка соединения — по порядку.',minutes:4,tags:['регистрация','начать','мастер'],action:'connect',related:['telegram','golden-key','proxy'],sections:[
  kbSection('Перед началом','Подготовьте свой магазин FunPay, отдельного рабочего Telegram-бота и прокси. В «Финансах» проверьте состояние доступа: наличие карточки тарифа само по себе не означает, что тариф активен.'),
  kbSection('Пройдите мастер',[],{steps:['Откройте «Подключить FunPay» в верхней панели кабинета.','Создайте бота через официальный @BotFather в Telegram. Токен вставьте в поле мастера ZetSlay.','Откройте своего рабочего бота и отправьте команду привязки с кодом, который показывает мастер. Дождитесь подтверждения.','Вставьте Golden Key своего аккаунта FunPay в поле кабинета.','Добавьте прокси, проверьте данные и запустите проверку соединения.','Дождитесь подтверждённого подключения. На «Главной» нажмите «Обновить данные» и проверьте имя магазина.']}),
  kbSection('Что происходит после проверки','Чтение магазина и разрешение автоматизации — разные действия. Установка плагина не заменяет его настройки: отдельно проверьте включение, привязки и разрешения на покупку или отправку сообщений.',{notice:'Токен бота, Golden Key и пароль прокси вводятся только в веб-кабинете. Поддержке они не нужны.'})]},
 {id:'golden-key',category:'connection',title:'Где взять Golden Key',summary:'Как найти cookie своего аккаунта и передать её в мастер подключения.',minutes:3,tags:['golden_key','ключ','cookie','Chrome','компьютер','Android','iPhone'],action:'connect',related:['connect','connection-errors'],sections:[
  kbSection('На компьютере',[],{steps:['Откройте https://funpay.com/ и войдите в нужный аккаунт. Проверьте имя магазина.','Откройте инструменты разработчика браузера. В Chrome на Windows это F12 или Ctrl+Shift+I.','Перейдите в Application → Storage → Cookies и выберите origin https://funpay.com.','Найдите строку golden_key. Скопируйте только значение из колонки Value, без имени cookie и кавычек.','Вернитесь в мастер ZetSlay и вставьте значение в поле Golden Key.']}),
  kbSection('Если ключа не видно','Проверьте, что вы вошли на FunPay и выбрали cookies именно этого сайта. Не устанавливайте случайные расширения для извлечения ключей и не запускайте чужие команды в консоли.',{link:{href:'https://developer.chrome.com/docs/devtools/application/cookies',label:'Инструкция Chrome: просмотр cookies'}}),
  kbSection('На телефоне','Мобильные браузеры обычно не предоставляют такую же панель cookies. Для первичного получения ключа удобнее использовать личный компьютер; затем кабинетом можно пользоваться с телефона.',{notice:'Golden Key даёт доступ к аккаунту. Не отправляйте его в Telegram, на скриншотах или в обращениях поддержки.'})]},
 {id:'proxy',category:'connection',title:'Как правильно указать прокси',summary:'Поддерживаемые форматы, отдельные порты HTTP и SOCKS5 и стабильный маршрут.',minutes:3,tags:['адрес','сервер','порт','login','password','http','https','socks5'],action:'connect',related:['connection-errors','connect'],sections:[
  kbSection('Выберите формат','Вместо примеров подставьте реквизиты своего прокси. Формат «сервер:порт:логин:пароль» распознаётся как HTTP. Для SOCKS5 укажите протокол явно и используйте его порт.',{code:'proxy.example:8000:LOGIN:PASSWORD\nhttp://LOGIN:PASSWORD@proxy.example:8000\nsocks5://LOGIN:PASSWORD@proxy.example:8001'}),
  kbSection('Проверьте реквизиты',[],{steps:['Сверьте сервер, порт, логин и пароль с данными провайдера. Не добавляйте пробелы и переносы строк.','Уточните, какой протокол поддерживает выбранный порт. HTTP и SOCKS5 могут использовать разные порты.','Для URL-формата специальные символы в логине и пароле требуют URL-кодирования. Для HTTP проще использовать четыре поля через двоеточие.','Выполните проверку в мастере ZetSlay. Доступность произвольного сайта через прокси ещё не подтверждает доступность FunPay.']}),
  kbSection('Стабильность важнее одной удачной проверки','Выбирайте предсказуемый маршрут для магазина. При ротации выходного IP соединение может меняться; успешный запрос не гарантирует стабильность следующих запросов.',{notice:'Не публикуйте адрес прокси вместе с логином и паролем. После замены повторно проверьте подключение.'})]},
 {id:'telegram',category:'connection',title:'Привязать рабочего Telegram-бота',summary:'Чем рабочий бот отличается от входа через Telegram и как открыть меню.',minutes:2,tags:['start','menu','BotFather','код','привязка'],action:'connect',related:['connect','dialogs'],sections:[
  kbSection('Два разных назначения','Вход через Telegram авторизует вас в ZetSlay. Рабочий бот магазина принимает уведомления и команды управления. Авторизация в сервисе не привязывает рабочего бота автоматически.'),
  kbSection('Подключение',[],{steps:['Получите токен своего бота у @BotFather и сохраните его в мастере подключения.','Откройте чат именно с этим ботом. Отправьте команду /start с кодом из мастера, полностью и без изменений.','Дождитесь подтверждения в боте и кабинете. Затем откройте меню командой /menu.','Если бот ожидает ввод настройки, /cancel отменит текущий шаг.']}),
  kbSection('Если бот молчит','Проверьте имя бота, актуальность кода и результат сохранения токена в мастере. Не удаляйте подключение магазина: передайте поддержке имя бота и время попытки, без токена.') ]},
 {id:'connection-errors',category:'diagnostics',title:'Магазин не подключается: что проверить',summary:'PROXY_TIMEOUT, HTTP 403 и ошибки состояния — это разные этапы отказа.',minutes:4,tags:['PROXY_TIMEOUT','403','INVALID_STATE','PLATFORM_UNAVAILABLE','verifying_read_only','недоступно','ошибка','прокси'],action:'connect',related:['proxy','support'],sections:[
  kbSection('PROXY_TIMEOUT','Запрос не завершился за отведённое время. Если диагностика показывает proxy_connect и CONNECT=0, защищённый туннель ещё не создан: ответ FunPay и авторизация магазина не проверены. Это не доказывает, что Golden Key неверный.'),
  kbSection('CONNECT=200 и HTTP=403','Туннель создан, но целевой HTTPS-запрос получил отказ. Это отличается от таймаута. По одному статусу нельзя установить точную причину или обещать, что смена браузерного заголовка решит проблему.'),
  kbSection('«Действие недоступно в текущем состоянии»','Откройте мастер и посмотрите сохранённый этап. Проверка подключения, активность тарифа и подтверждённая привязка бота должны быть согласованы. Не сбрасывайте рабочий кабинет и не создавайте новый аккаунт ради обхода ошибки.'),
  kbSection('Для поддержки',[],{steps:['Укажите имя рабочего бота и время попытки с часовым поясом.','Передайте точный код ошибки и этап диагностики.','Скройте ключи, токены, логин и пароль прокси на скриншотах.','Сообщите, какая проверка была успешна, где и когда. Успех другой проверки не заменяет результат текущего подключения.']})]},
 {id:'dashboard',category:'store',title:'Как читать статистику на «Главной»',summary:'Периоды, валюты, продажи и возвраты без смешивания сумм.',minutes:2,tags:['день','неделя','месяц','статистика','средний чек','баланс'],action:'dashboard',related:['orders','finances'],sections:[
  kbSection('Выберите период','«Сегодня» начинается в 00:00 по Москве. «7 дней» и «30 дней» включают текущий день и предыдущие 6 или 29 дней. «Все данные» показывает весь загруженный список, а не гарантированную историю магазина за всё время.'),
  kbSection('Что считается','Период определяется датой создания заказа. Сумма продаж и средний заказ исключают отмены и возвраты; суммы показаны до комиссий. Разные валюты считаются отдельно. Возвраты группируются по дате создания заказа, а не по неизвестной дате возврата.'),
  kbSection('Почему стоит прочерк','Если FunPay не передал достоверную дату или сумму, сервис не придумывает значение. Заказы без даты не входят в выбранный период. Полная история может отсутствовать в загруженном списке.',{notice:'Баланс магазина — текущий снимок FunPay. Он не является выручкой за выбранный период.'})]},
 {id:'orders',category:'store',title:'Заказы: даты, суммы и статусы',summary:'Как проверить заказ и отличить данные площадки от предположения.',minutes:2,tags:['заказ','оплачен','завершён','возврат','дата'],action:'orders',related:['dashboard','kosell-delivery'],sections:[
  kbSection('Начните с номера заказа','Откройте «Заказы» и найдите нужный номер. Сверьте покупателя, товар, валюту, сумму и статус с FunPay. Данные кабинета относятся к последней синхронизации.'),
  kbSection('Дата и статус','Дата создания и время обновления снимка — разные значения. Если дата заказа не распознана, используйте информацию площадки. «Возвращён» — статус заказа, а не подтверждение возврата денег у стороннего поставщика.'),
  kbSection('Проверьте выдачу отдельно','Оплата заказа не доказывает, что плагин купил товар и доставил его покупателю. Для автоматизированного заказа дополнительно проверьте задачу плагина, результат поставщика и сообщение в чате.') ]},
 {id:'dialogs',category:'store',title:'Сообщения покупателей и ответы',summary:'Переписка в кабинете и ответы через своего рабочего бота.',minutes:2,tags:['диалог','чат','reply','ответить','Telegram','уведомления'],action:'messages',related:['telegram','support'],sections:[
  kbSection('В кабинете','Откройте «Сообщения», выберите диалог и проверьте собеседника перед отправкой. Обновление подтягивает доступную переписку магазина; отсутствие нового сообщения в снимке не доказывает, что его не было на площадке.'),
  kbSection('В Telegram','Для ответа используйте «Ответить» на уведомление покупателя в подключённом рабочем боте. Ответ должен быть привязан к уведомлению с конкретным диалогом. Произвольное сообщение в чат бота не следует считать ответом покупателю.'),
  kbSection('Если доставка не подтверждена','Проверьте состояние отправки и сам диалог FunPay. Не отправляйте текст многократно подряд: при неопределённом результате повтор может создать дубликат. Передайте поддержке время, номер заказа или диалога и текст ошибки.') ]},
 {id:'lots',category:'store',title:'Лоты и товары: найти и проверить',summary:'Фильтры, наличие и переход к редактору FunPay.',minutes:2,tags:['каталог','товар','остаток','цена','скрытый','редактировать'],action:'lots',related:['mass-prices','sales-pause','clone'],sections:[
  kbSection('Работа со списком','Откройте «Лоты и товары» и обновите данные. Используйте поиск и фильтр состояния; откройте карточку нужного лота, чтобы сверить ID, категорию, цену и остаток.'),
  kbSection('Что означает «не передан»','Неизвестный остаток не равен нулю. Скрытый товар может быть выключен продавцом или ограничен площадкой. Для точной проверки и ручного редактирования перейдите из карточки на FunPay.'),
  kbSection('Массовые изменения','Для переоценки, клонирования и паузы продаж используйте соответствующие плагины. Перед запуском проверьте сводку выбранных лотов: просмотр каталога сам по себе не изменяет цены и наличие.') ]},
 {id:'plugins',category:'plugins',title:'Установить и настроить плагин',summary:'Редкость, варианты доступа и разница между включением и автопокупкой.',minutes:3,tags:['обычный','продвинутый','ультра','легендарный','установка','подписка'],action:'plugins',related:['finances','kosell-start','support'],sections:[
  kbSection('Откройте карточку','В каталоге используйте фильтры и сортировку. В «Подробнее» прочитайте описание, ограничения, варианты доступа и настройки. Редкость — категория каталога, а не гарантия результата конкретной операции.'),
  kbSection('Проверьте доступ и разрешения','Разовый доступ к плагину и доступ по подписке — разные варианты. Подписка включает категории, перечисленные в её условиях. Наличие цены или кнопки в описании не подтверждает успешную оплату.'),
  kbSection('Первый запуск',[],{steps:['Установите и включите модуль, если действие доступно вашему кабинету.','Сохраните его настройки и нужные привязки товаров.','Отдельно проверьте разрешения на автопокупку, отправку сообщений и управление лотами.','Начните с одного подходящего лота. Проверьте полный путь заказа до выдачи, прежде чем расширять ассортимент.']}),
  kbSection('Отключение','Остановите активные массовые задания и проверьте временные предложения перед отключением. Выключение плагина не отменяет уже выполненные покупки и изменения у внешнего сервиса.') ]},
 {id:'mass-prices',category:'plugins',title:'Mass Price Editor: переоценка по сводке',summary:'Выбрать разделы, проверить действие и остановить дальнейшие изменения.',minutes:3,tags:['массовое','цены','скидка','процент','mass_price_editor'],action:'plugin',plugin:'zetslay.mass-price-editor',related:['lots','sales-pause'],sections:[
  kbSection('Подготовка',[],{steps:['Откройте Mass Price Editor в меню плагинов рабочего бота.','Выберите игру и нужные обычные разделы товаров.','Выберите фиксированную цену, добавление/вычитание суммы или изменение в процентах.','Введите значение. Внимательно проверьте выбранные разделы и действие в сводке.','Подтвердите запуск только после проверки. Следите за прогрессом и ошибками.']}),
  kbSection('Ограничения','Игровая валюта исключена из этого редактора. Цены округляются до копеек; минимальная допустимая цена — 0,01. Уменьшение в процентах и вычитание суммы имеют разный результат.'),
  kbSection('Стоп и неизвестный результат','Стоп прекращает следующие изменения после текущего запроса. Уже обработанные лоты не откатываются автоматически. При неизвестном результате сначала проверьте цену лота на FunPay, затем решайте, нужен ли новый запуск.') ]},
 {id:'sales-pause',category:'plugins',title:'Пауза продаж: скрыть и вернуть лоты',summary:'Список восстановления, стоп и ошибки проверки редактора.',minutes:3,tags:['деактиватор','выключить','активировать','PAUSE_FORM_CHANGED','unsupported_control'],action:'plugin',plugin:'zetslay.sales-pause',related:['lots','support'],sections:[
  kbSection('Как запускать','Выберите отключение или восстановление в меню плагина. Сначала подготовьте сводку, проверьте состав товаров и подтвердите изменения. Подготовка сводки читает лоты, но не меняет их состояние.'),
  kbSection('Что восстанавливается','Плагин хранит сведения о товарах, отключённых им. Ошибка активации не должна считаться успешным восстановлением. Проверьте список товаров, требующих внимания, и реальное состояние на FunPay.'),
  kbSection('PAUSE_FORM_CHANGED','Плагин не подтвердил формат редактора. Это может зависеть от категории товара. Не пытайтесь многократно запускать всю очередь: передайте поддержке код, ID проблемных лотов и этап операции.',{notice:'Стоп не отменяет уже отправленный запрос. До новой сводки проверьте итог предыдущей операции.'}) ]},
 {id:'clone',category:'plugins',title:'Lot Cloner: копия собственного лота',summary:'Как выбрать оригинал и проверить копию перед публикацией.',minutes:2,tags:['клонирование','дублирование','clone_lot','копия'],action:'plugin',plugin:'zetslay.lot-cloner',related:['lots','kosell-stock'],sections:[
  kbSection('Создание копии',[],{steps:['Найдите ID собственного обычного лота в его ссылке на FunPay.','Откройте Lot Cloner в меню рабочего бота или введите /clone_lot с ID.','После результата проверьте новый ID, категорию, описания, цену и изображения.','Копия создаётся выключенной. Внесите нужные правки и отдельно активируйте её.']}),
  kbSection('Если ответ неопределённый','Сначала проверьте список предложений FunPay. Повтор команды без проверки может создать второй экземпляр. Копирование не переносит товар в категорию другой игры.') ]},
 {id:'reviews',category:'plugins',title:'Отзывы: напоминания и бонусы',summary:'Триггеры, задержки, переменные и отдельный подарок за отзыв.',minutes:3,tags:['Review Reminder','Auto Review Bonus','отзыв','reminder','бонус','подарок'],action:'plugins',related:['plugins','orders'],sections:[
  kbSection('Review Reminder','Выберите событие запуска — оплату или подтверждение заказа. Настройте первое сообщение и задержку. Второе напоминание включается отдельно, а его задержка отсчитывается после первого сообщения.'),
  kbSection('Шаблоны','Используйте поддерживаемые переменные для имени покупателя, номера и названия заказа. Перед отправкой проверяется состояние заказа: оставленный отзыв или возврат должны остановить напоминания.'),
  kbSection('Auto Review Bonus','Это отдельный модуль с пулом подарков и защитой от повторной выдачи. Проверьте условие оценки, наличие подарков, ограничения покупателя и текст сообщения. Условия подарка должны быть понятны покупателю; не обещайте содержимое, которого нет в пуле.') ]},
 {id:'kosell-start',category:'kosell',title:'Kosell Rent: первый рабочий лот',summary:'API-ключ, лимит, привязка игры и проверка первой выдачи.',minutes:5,tags:['аренда','API','лимит одной покупки','RUB','USD','автопокупка'],action:'plugin',plugin:'zetslay.kosell-rent',related:['kosell-stock','kosell-delivery'],sections:[
  kbSection('Подключите поставщика','Сохраните API-ключ Kosell в веб-настройках плагина. Проверьте баланс и загрузите игры. Сохранённый ключ ещё не доказывает успешность будущей покупки: наличие аккаунтов и баланс меняются.'),
  kbSection('Что вводить в лимит','«Лимит одной покупки / продления» — максимальный разрешённый расход у Kosell на одну операцию в выбранной валюте, а не цена вашего лота и не общий бюджет. Сверьте его с серверной себестоимостью нужного срока. Слишком маленький лимит остановит операцию; большой не заменяет проверку маржи.'),
  kbSection('Создайте привязку',[],{steps:['Выберите свой обычный лот FunPay нужной игры.','Укажите ID лота и его обычного раздела, продукт Kosell и часы аренды на одну единицу товара.','Проверьте лот и сохраните привязку. Убедитесь, что она появилась в списке.','Отдельно включите автопокупку, если хотите автоматическую обработку новых заказов.','Проверьте задачу нового заказа, аренду у поставщика и доставку покупателю. Старые заказы до включения автоматически не покупаются.']}),
  kbSection('Перед расширением','Не включайте массовый ассортимент до проверки одной полной цепочки. Сообщения с паролем и Steam Guard должны уходить покупателю, которому принадлежит нужный заказ.') ]},
 {id:'kosell-stock',category:'kosell',title:'Kosell Rent: наличие, цены и массовая витрина',summary:'Шаблон нужной категории, наценка и причины пропуска сроков.',minutes:4,tags:['ассортимент','шаблон','наценка','баланс','привязки','план','очередь','создание лотов'],action:'plugin',plugin:'zetslay.kosell-rent',related:['kosell-start','clone','kosell-delivery'],sections:[
  kbSection('Скрытие и переоценка','Разрешение управления привязанными лотами включается отдельно. Затем выберите скрытие при отсутствии аккаунтов или недостатке баланса и пересчёт цены. Общая наценка применяется там, где нет индивидуальной. Комиссия FunPay в эту наценку автоматически не включается.'),
  kbSection('Критично: категория шаблона','Название игры Kosell не определяет категорию FunPay. Новый лот наследует категорию, параметры и изображения выбранного вами шаблона. Для каждой игры выбирайте собственный лот-шаблон в соответствующем разделе FunPay.',{notice:'Шаблон Escape the Backrooms создаст лоты в этом разделе даже при названии другой игры. Переименование не исправляет категорию.'}),
  kbSection('План и очередь',[],{steps:['Сопоставьте каждую игру Kosell с ID её собственного лота-шаблона.','Выберите сроки в часах и подготовьте план. Просмотр плана не создаёт лоты.','Раскройте причины пропуска. «Уже есть привязка или задание» означает, что для этой пары уже найдена связка или работа в очереди.','Проверьте план и подтвердите создание. «В очереди» ещё не означает, что лот опубликован.','Сверьте готовые предложения на FunPay: категория, цена, сроки и активность.']}),
  kbSection('Возвращение в продажу','Плагин возвращает только лоты, скрытые им самим. Ручные изменения могут остановить управление до вашей проверки. Не меняйте параллельно те же товары массовым редактором.') ]},
 {id:'kosell-delivery',category:'kosell',title:'Kosell Rent: заказ оплачен, но аккаунт не выдан',summary:'Проверить аренду, расход и отправку, не создавая повторное списание.',minutes:4,tags:['KOSELL_UNAVAILABLE','discovering','unknown','не выдал','неизвестный результат','ошибка','возврат'],action:'plugin',plugin:'zetslay.kosell-rent',related:['kosell-start','support','orders'],sections:[
  kbSection('Сначала сохраните номер заказа','Откройте «Заказы и аренды» плагина. Сверьте номер заказа, покупателя, состояние задачи и код ошибки. Одна ошибка чтения заказа не доказывает, что запрос на покупку уже отправлялся.'),
  kbSection('Проверьте три отдельных результата',[],{steps:['Распознан ли лот и найдена ли его привязка к игре и сроку?','Есть ли подтверждённая аренда у Kosell и её UID, известен ли расход?','Было ли подтверждено сообщение с доступом в нужном диалоге FunPay?']}),
  kbSection('Неизвестный результат покупки','Если покупка могла выполниться, но ответ потерян, автоматический повтор заблокирован. Не создавайте вторую аренду наугад. Сначала проверьте активные аренды и операцию поставщика.',{notice:'«Повторно выдать» использует существующую аренду; это не новая покупка. Действие требует вашей проверки и подтверждения.'}),
  kbSection('Если вы сделали возврат','Возврат покупателю на FunPay не равен возврату расхода Kosell. Проверьте действующую аренду и списание отдельно. Досрочное завершение аренды у поставщика может не возвращать средства. Передайте поддержке номер заказа, UID аренды при наличии и код ошибки — без пароля аккаунта.') ]},
 {id:'kosell-buyer',category:'kosell',title:'Kosell Rent: команды покупателя и продление',summary:'Steam Guard, смена пароля, выход из сессий и платные часы.',minutes:3,tags:['steamcode','пароль','кик','продление','бонус','часы'],action:'plugin',plugin:'zetslay.kosell-rent',related:['kosell-start','kosell-delivery'],sections:[
  kbSection('Команды в чате FunPay','Steam Guard запрашивается командой !steamcode НОМЕР_ЗАКАЗА. Разрешения на !пароль и !кик задаются отдельно; операции выполняются с подтверждением покупателя и проверкой принадлежности заказа.'),
  kbSection('Платное продление','Команда !продление ЧАСЫ НОМЕР_ЗАКАЗА создаёт оплачиваемое личное предложение при соответствующих разрешениях. Дополнительные часы добавляются после оплаты тем же покупателем. Для временных предложений требуется разрешение управления лотами.'),
  kbSection('Бонус за отзыв','Бонусные часы оплачиваются из вашего баланса Kosell. Настройте минимальную оценку, количество часов и лимит расхода. Проверка оценки и статуса перед списанием не является обещанием бесплатного продления со стороны поставщика.'),
  kbSection('Перед отключением','Проверьте и закройте временные предложения, которые больше не должны принимать оплату. Активная аренда и очередь отправки требуют отдельной проверки.') ]},
 {id:'robux',category:'plugins',title:'Robux Relay: Game Pass и лимиты',summary:'Аккаунт продавца, единицы товара и подтверждение покупки Game Pass.',minutes:3,tags:['Robux','Roblox','Game Pass','ROBLOSECURITY','Robux Relay'],action:'plugin',plugin:'zetslay.robux-relay',related:['plugins','orders','support'],sections:[
  kbSection('Подготовьте источник','Добавьте свой аккаунт Roblox через защищённую веб-форму и проверьте его баланс. Cookie .ROBLOSECURITY не отправляйте в бот или поддержку. Задайте резерв, лимит одного списания и дневной бюджет: здесь расходы измеряются в Robux.'),
  kbSection('Привязка и покупатель','Свяжите лот или подходящий валютный раздел FunPay с количеством Robux за единицу товара. У валютного раздела привязка охватывает его новые заказы: внимательно проверьте единицы. Затем покупатель передаёт Game Pass и подтверждает проверенные данные.'),
  kbSection('Проверьте результат','Очередь, покупка, подтверждение владения Game Pass и уведомление — отдельные этапы. Неопределённое списание входит в дневной бюджет. Аварийный стоп запрещает следующие действия; отправленный запрос может завершиться.',{notice:'Снятие приёма новых заказов не отменяет уже созданную очередь. При ошибке сначала проверьте конкретную задачу и Game Pass.'}) ]},
 {id:'stars',category:'plugins',title:'Stars Relay: получатель и выдача Stars',summary:'Как проверить @username и отличить очередь от подтверждённой отправки.',minutes:3,tags:['Stars','звезды','Telegram Stars','получатель','кошелек'],action:'plugin',plugin:'zetslay.stars-relay',related:['plugins','orders','support'],sections:[
  kbSection('Настройка','Откройте Stars Relay и настройте подключение поставщика и кошелька в веб-кабинете. Проверьте доступные лимиты и привязку лота. Секретная фраза кошелька и сессия поставщика не предназначены для Telegram или поддержки.'),
  kbSection('Данные покупателя','Задача может ожидать @username получателя и его подтверждение. Сверьте получателя и количество Stars до оплаты операции. Номер заказа должен соответствовать именно этому покупателю.'),
  kbSection('Результат операции','«В очереди» не означает выдачу. Проверьте подтверждённый результат отправки и уведомление покупателю. При неопределённой операции сначала выясните существующий результат; повторная отправка может повторно потратить средства.') ]},
 {id:'tiktok-market',category:'plugins',title:'TikTok LZT Market: выбор и выдача аккаунта',summary:'Критерии подбора, лимиты расходов и контроль результата поставщика.',minutes:3,tags:['TikTok LZT Market','LZT','тикток','фильтры','баланс'],action:'plugin',plugin:'zetslay.tiktok-lzt-market',related:['plugins','orders','support'],sections:[
  kbSection('Доступ к поставщику','Сохраните API-ключ в веб-настройках и проверьте баланс. Настройте лимит одной покупки, дневной бюджет и минимальную разницу до комиссий. Отдельно включите автоматическую обработку и проверьте состояние серверной очереди.'),
  kbSection('Критерии и привязки','Привяжите собственный лот и задайте критерии подходящего TikTok-аккаунта. Проверьте результат поиска перед запуском. Наличие товара в поиске не резервирует его навсегда и не подтверждает последующую покупку.'),
  kbSection('После оплаты заказа','Сверьте выбранный аккаунт, факт покупки у поставщика и отправку данных покупателю. Ошибка API, недостаток баланса или неизвестное списание не запускают автовозврат. Старые заказы при первом включении пропускаются.',{notice:'Повтор выдачи и повтор покупки — разные действия. При неизвестном расходе сначала проверьте операцию у поставщика.'}) ]},
 {id:'roblox-market',category:'plugins',title:'Roblox LZT Market: привязки и бюджет',summary:'Подобрать Roblox-аккаунт для лота и не повторить неизвестную покупку.',minutes:3,tags:['Roblox LZT Market','LZT','роблокс','покупка','критерии'],action:'plugin',plugin:'zetslay.roblox-lzt-market',related:['plugins','orders','support'],sections:[
  kbSection('Настройка','Сохраните ключ поставщика, проверьте баланс и задайте ограничения расходов. Привяжите свой лот к критериям Roblox-аккаунта. Автопокупка включается отдельно от установки плагина.'),
  kbSection('Условия обработки','Автоматически обрабатывается одна единица в оплаченном заказе RUB. Дневной бюджет учитывает зарезервированные и неопределённые расходы. Прежние заказы первого снимка пропускаются.'),
  kbSection('Покупка и доставка','Проверьте задачу заказа, подтверждённый результат покупки и выдачу в чате FunPay. При неизвестном списании не возвращайте заказ в покупку наугад. Ошибка поставщика не равна доказательству отсутствия покупки или автоматическому возврату денег.') ]},
 {id:'finances',category:'account',title:'Тарифы, разовый доступ и баланс',summary:'Что входит в подписку и почему баланс FunPay учитывается отдельно.',minutes:2,tags:['оплата','149','подписка','пополнить','промокод','навсегда'],action:'billing',related:['plugins','dashboard'],sections:[
  kbSection('Актуальные условия — в «Финансах»','Откройте тарифы, выберите срок и изучите полную сумму за период. Каждый следующий тариф включает предыдущие категории. Состав доступа сверяйте с текущей карточкой тарифа, а не с цветом обложки.'),
  kbSection('Два варианта доступа','Разовая покупка предоставляет бессрочный доступ к конкретному плагину на условиях договора. Подписка предоставляет доступ на оплаченный срок к перечисленным категориям. Это не оплата товара у Kosell или другого поставщика.'),
  kbSection('Разные балансы','Баланс FunPay — средства вашего магазина на площадке. Баланс ZetSlay предназначен для доступа к сервису. Баланс Kosell оплачивает аренды у поставщика. Они не взаимозаменяемы и не переводятся автоматически.'),
  kbSection('Перед оплатой','Проверьте доступность оплаты в интерфейсе и текущие условия. Если функция показывает «Оплата готовится к запуску», пополнение ещё недоступно. Юридические документы и контакты доступны по ссылкам кабинета.') ]},
 {id:'profile',category:'account',title:'Профиль и публичная карточка автора',summary:'Личные настройки и сведения, которые можно показывать другим пользователям.',minutes:2,tags:['аккаунт','имя','аватар','автор','маркетплейс','конфиденциальность'],action:'profile',related:['support','finances'],sections:[
  kbSection('Личные настройки','В «Профиле» проверьте сведения аккаунта и доступные настройки. Изменение имени профиля не меняет владельца подключённого магазина и не создаёт новый кабинет.'),
  kbSection('Публичная карточка','Публичные сведения автора настраиваются отдельно от приватных данных аккаунта. Публикуйте только то, что готовы показывать другим пользователям. Подготовка профиля не означает, что продажи сторонних плагинов уже доступны.'),
  kbSection('Секреты подключения','Golden Key, токены и реквизиты прокси не являются описанием профиля. Менять их нужно в соответствующих защищённых полях настройки подключения.') ]},
 {id:'support',category:'diagnostics',title:'Что отправить поддержке',summary:'Короткий отчёт, с которым проблему можно воспроизвести и проверить.',minutes:2,tags:['поддержка','ошибка','диагностика','не сохраняется','не работает'],action:'support',related:['connection-errors','kosell-delivery'],sections:[
  kbSection('Соберите факты',[],{steps:['Название раздела или плагина и точное действие, которое не сработало.','Время ошибки и часовой пояс; имя рабочего бота.','Код и текст ошибки. Для заказа — его номер, для лота — его ID.','Что ожидали получить и что увидели фактически.','Скриншот после скрытия секретов и личных данных покупателей.']}),
  kbSection('Не пересылайте доступы','Не отправляйте Golden Key, токен бота, API-ключ поставщика, пароль прокси, пароли покупателей или одноразовые коды. Поддержке достаточно идентификаторов и диагностического результата.',{notice:'Не очищайте очередь и не повторяйте списание ради диагностики. Неопределённая операция требует проверки существующего результата.'}) ]}
]);
const kbState = {query:'',category:'all',article:null};
const kbEscape = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kbIcon = name => name==='arrow-left' ? '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="m14 6-6 6 6 6M8 12h12"/></svg>' : name==='link' ? '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="m10 13 4-4M8 15l-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0M16 9l2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(1 0) scale(.9)"/></svg>' : `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const kbNormalize = value => String(value||'').toLocaleLowerCase('ru-RU').replace(/ё/g,'е').replace(/[^\p{L}\p{N}_]+/gu,' ').trim();
function kbSearch(query,category='all') {
 const terms=kbNormalize(query).split(/\s+/).filter(Boolean);
 return KB_ARTICLES.filter(a=>category==='all'||a.category===category).map(a=>{
  const title=kbNormalize(a.title+' '+a.summary+' '+a.tags.join(' '));
  const text=title+' '+kbNormalize(a.sections.map(s=>s.title+' '+s.body.join(' ')+' '+(s.steps||[]).join(' ')+' '+(s.code||'')+' '+(s.notice||'')).join(' '));
  return {article:a,match:terms.every(t=>text.includes(t)),score:terms.reduce((n,t)=>n+(kbNormalize(a.title).includes(t)?3:title.includes(t)?1:0),0)};
 }).filter(x=>x.match).sort((a,b)=>b.score-a.score).map(x=>x.article);
}
function kbCard(a) {
 const c=KB_CATEGORIES.find(c=>c.id===a.category);
 return `<button type="button" class="kb-card" data-kb-open="${a.id}"><span class="kb-card-top"><span class="kb-icon kb-icon--${c.color}">${kbIcon(c.icon)}</span><span>${a.minutes} мин</span></span><strong>${kbEscape(a.title)}</strong><span class="kb-card-desc">${kbEscape(a.summary)}</span><span class="kb-card-footer">${kbEscape(c.name)}${kbIcon('chevron')}</span></button>`;
}
function kbRenderList() {
 const root=document.querySelector('[data-knowledge-base]');if(!root)return;
 const list=kbSearch(kbState.query,kbState.category);
 root.querySelector('[data-kb-count]').textContent=String(list.length);
 root.querySelector('[data-kb-results-title]').textContent=kbState.query?'Результаты поиска':kbState.category==='all'?'Все инструкции':KB_CATEGORIES.find(c=>c.id===kbState.category)?.name||'Все инструкции';
 root.querySelector('[data-kb-results]').innerHTML=list.length?list.map(kbCard).join(''):'<div class="kb-empty"><span class="kb-icon">'+kbIcon('search')+'</span><h3>Ничего не найдено</h3><p>Попробуйте номер ошибки, название плагина или более короткий запрос.</p><button class="button button--ghost" type="button" data-kb-reset>Сбросить поиск и фильтры</button></div>';
 root.querySelectorAll('[data-kb-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kbCategory===kbState.category)));
 root.querySelector('[data-kb-clear]').hidden=!kbState.query;
}
function kbLink(id) {const url=new URL(location.pathname,location.origin);url.searchParams.set('kb',id);url.hash='guide';return url.href;}
function kbSectionMarkup(s,index) {
 return `<section id="kb-section-${index}"><h3 tabindex="-1">${kbEscape(s.title)}</h3>${s.body.map(p=>`<p>${kbEscape(p)}</p>`).join('')}${s.steps?`<ol>${s.steps.map(p=>`<li>${kbEscape(p)}</li>`).join('')}</ol>`:''}${s.code?`<pre><code>${kbEscape(s.code)}</code></pre>`:''}${s.notice?`<aside class="kb-callout">${kbIcon('shield')}<p>${kbEscape(s.notice)}</p></aside>`:''}${s.link?`<a class="kb-text-link" href="${kbEscape(s.link.href)}" target="_blank" rel="noopener noreferrer">${kbEscape(s.link.label)} ${kbIcon('external')}</a>`:''}</section>`;
}
function kbAction(a) {
 if(a.action==='connect')return '<button class="button button--primary" type="button" data-open-connect>Открыть мастер подключения</button>';
 if(a.action==='support')return '<a class="button button--primary" href="https://t.me/zetslaysupport" target="_blank" rel="noopener noreferrer">Написать поддержке</a>';
 const target=a.action==='plugin'?`plugins/${a.plugin}`:a.action;
 return `<button class="button button--primary" type="button" data-view-link="${target}">${a.action==='plugin'?'Открыть плагин':'Перейти в раздел'} ${kbIcon('chevron')}</button>`;
}
function kbOpen(id,{updateUrl=true,focus=true}={}) {
 const article=KB_ARTICLES.find(a=>a.id===id);const root=document.querySelector('[data-knowledge-base]');if(!article||!root)return false;
 kbState.article=id;
 root.querySelector('[data-kb-library]').hidden=true;
 const reader=root.querySelector('[data-kb-reader]');reader.hidden=false;
 const c=KB_CATEGORIES.find(c=>c.id===article.category);
 reader.innerHTML=`<div class="kb-reader-bar"><button type="button" class="kb-back" data-kb-back>${kbIcon('arrow-left')} Все инструкции</button><button type="button" class="kb-back" data-kb-copy>Скопировать ссылку ${kbIcon('link')}</button></div><div class="kb-reader-layout"><article class="kb-article"><header><span class="kb-article-meta"><span class="kb-icon kb-icon--${c.color}">${kbIcon(c.icon)}</span>${kbEscape(c.name)}<span>· ${article.minutes} мин чтения</span></span><h2 tabindex="-1" data-kb-article-title>${kbEscape(article.title)}</h2><p class="kb-lead">${kbEscape(article.summary)}</p></header><div class="kb-article-body">${article.sections.map(kbSectionMarkup).join('')}</div><footer>${kbAction(article)}<span>Редакция инструкции: 10 октября 2026</span></footer></article><aside class="kb-toc"><h3>В этой инструкции</h3><nav aria-label="Содержание статьи">${article.sections.map((s,i)=>`<button type="button" data-kb-section="${i}">${kbEscape(s.title)}</button>`).join('')}</nav><div class="kb-reader-help"><strong>Нужна помощь?</strong><p>Опишите проблему и приложите код ошибки. Ключи и пароли не отправляйте.</p><a href="https://t.me/zetslaysupport" target="_blank" rel="noopener noreferrer">@zetslaysupport ${kbIcon('external')}</a></div></aside></div><section class="kb-related"><h3>Может пригодиться</h3><div class="kb-grid">${article.related.map(id=>KB_ARTICLES.find(a=>a.id===id)).filter(Boolean).map(kbCard).join('')}</div></section><p class="kb-copy-status" data-kb-copy-status role="status" aria-live="polite"></p><input class="kb-share-link" data-kb-share-link readonly aria-label="Ссылка на инструкцию" hidden>`;
 if(updateUrl)history.replaceState(null,'',kbLink(id));
 if(focus)reader.querySelector('[data-kb-article-title]')?.focus();
 return true;
}
function kbClose({focus=true}={}) {
 const root=document.querySelector('[data-knowledge-base]');if(!root)return;
 const previous=kbState.article;kbState.article=null;
 root.querySelector('[data-kb-reader]').hidden=true;root.querySelector('[data-kb-library]').hidden=false;
 const url=new URL(location.href);url.searchParams.delete('kb');history.replaceState(null,'',url.href);
 kbRenderList();
 if(focus)(root.querySelector(`[data-kb-open="${previous}"]`)||root.querySelector('[data-kb-search]'))?.focus();
}
async function kbCopy() {
 const id=kbState.article;if(!id)return;
 const root=document.querySelector('[data-knowledge-base]');const link=kbLink(id);
 try {await navigator.clipboard.writeText(link);if(kbState.article===id)root.querySelector('[data-kb-copy-status]').textContent='Ссылка на инструкцию скопирована.';}
 catch {if(kbState.article!==id)return;const input=root.querySelector('[data-kb-share-link]');input.hidden=false;input.value=link;input.focus();input.select();root.querySelector('[data-kb-copy-status]').textContent='Выделенная ссылка готова к копированию.';}
}
function kbInit() {
 const root=document.querySelector('[data-knowledge-base]');if(!root)return;
 root.querySelector('[data-kb-categories]').innerHTML=`<button type="button" data-kb-category="all" aria-pressed="true">Все темы <span>${KB_ARTICLES.length}</span></button>`+KB_CATEGORIES.map(c=>`<button type="button" data-kb-category="${c.id}" aria-pressed="false">${kbEscape(c.name)} <span>${KB_ARTICLES.filter(a=>a.category===c.id).length}</span></button>`).join('');
 root.querySelector('[data-kb-total]').textContent=String(KB_ARTICLES.length);
 kbRenderList();
 const initial=new URL(location.href).searchParams.get('kb');
 if(initial&&kbOpen(initial,{updateUrl:false,focus:false})&&typeof setView==='function')setView('guide',false);
 root.addEventListener('input',event=>{if(!event.target.matches('[data-kb-search]'))return;kbState.query=event.target.value.slice(0,160);if(kbState.article)kbClose({focus:false});kbRenderList();});
 root.addEventListener('click',event=>{
  const open=event.target.closest('[data-kb-open]');if(open){kbOpen(open.dataset.kbOpen);return;}
  if(event.target.closest('[data-kb-back]')){kbClose();return;}
  if(event.target.closest('[data-kb-copy]')){kbCopy();return;}
  const category=event.target.closest('[data-kb-category]');if(category){const value=category.dataset.kbCategory;if(value==='all'||KB_CATEGORIES.some(c=>c.id===value)){kbState.category=value;if(kbState.article)kbClose({focus:false});kbRenderList();}return;}
  if(event.target.closest('[data-kb-clear], [data-kb-reset]')){kbState.query='';if(event.target.closest('[data-kb-reset]'))kbState.category='all';root.querySelector('[data-kb-search]').value='';kbRenderList();root.querySelector('[data-kb-search]').focus();return;}
  const section=event.target.closest('[data-kb-section]');if(section){const target=root.querySelector(`#kb-section-${section.dataset.kbSection}`);target?.scrollIntoView({behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});target?.querySelector('h3')?.focus();}
 });
 root.addEventListener('keydown',event=>{if(event.key==='Escape'&&kbState.article){event.preventDefault();kbClose();}});
}
kbInit();
