import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('./kosell-rent.js',import.meta.url),'utf8');
function app(){const handlers={},calls=[],authState={token:'owner-session'},status={installation:{enabled:true},config:{automatic:false,currency:'RUB',maxSpendMinor:10000,guardEnabled:true,deliveryTemplate:'$login $password'},keyConfigured:true,workerEnabled:true,purchaseEnabled:true,deliveryEnabled:true,mappings:[],tasks:[],providerAccount:{username:'<script>bad</script>',balanceRubMinor:20000,balanceUsdMinor:400}};
 const ctx=vm.createContext({authState,console,queueMicrotask,FormData:class{constructor(form){this.data=form.values;}get(key){return this.data.get(key)??null;}has(key){return this.data.has(key);}},document:{addEventListener:(name,handler)=>handlers[name]=handler,querySelector:()=>null},escapeHtml:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),humanError:e=>e.message,renderPluginPage:()=>{},apiRequest:async(path,options)=>{calls.push({path,options});return status;}});vm.runInContext(source,ctx);return {ctx,handlers,calls,status,authState,run:s=>vm.runInContext(s,ctx)};}
test('Kosell renders settings only for installed plugin; secret key is never prefilled',async()=>{const f=app();assert.match(f.run('kosellRentMarkup({installed:false})'),/Установите плагин/);await f.run('loadKosellStatus()');const html=f.run('kosellRentMarkup({installed:true})');assert.match(html,/type="password" name="apiKey"/);assert.match(html,/autocomplete="off"/);assert.match(html,/Лимит одной покупки/);assert.match(html,/data-kosell-mapping/);assert.doesNotMatch(html,/<script>bad/);assert.match(html,/&lt;script&gt;bad/);assert.doesNotMatch(source,/(?:localStorage|sessionStorage)\.(?:setItem|getItem)/);});
test('API key is posted only through settings and is cleared before request',async()=>{const f=app();await f.run('loadKosellStatus()');const values=new Map([['apiKey','PRIVATE_KEY'],['currency','RUB'],['maxSpend','100,50'],['deliveryTemplate','$login $password'],['guardEnabled','on']]),input={value:'PRIVATE_KEY'},form={values,matches:s=>s.includes('data-kosell-settings'),querySelector:()=>input};await f.handlers.submit({target:form,preventDefault(){}});assert.equal(input.value,'');const post=f.calls.find(c=>c.path.endsWith('/settings'));assert.equal(post.options.method,'POST');assert.equal(post.options.body.apiKey,'PRIVATE_KEY');assert.equal(post.options.body.config.maxSpendMinor,10050);assert.ok(!post.path.includes('PRIVATE_KEY'));});
test('Private response from a logged-out session cannot populate another account UI',async()=>{const f=app();let done;f.ctx.apiRequest=()=>new Promise(resolve=>done=resolve);const loading=f.run('loadKosellStatus()');f.authState.token='different-session';done(f.status);await loading;assert.equal(f.run('kosellUi.status'),null);});
test('Unknown purchase exposes reconciliation, not a second buy button; actions require a preview',async()=>{const f=app();f.status.tasks=[{orderId:'ABC',status:'purchase_unknown',productName:'<img src=x>'},{orderId:'BCD',status:'delivery_unknown',rentalUid:'uid_1',productName:'Game',hours:24}];await f.run('loadKosellStatus()');const html=f.run('kosellRentMarkup({installed:true})');assert.match(html,/data-kosell-reconcile/);assert.match(html,/data-kosell-op="deliver"/);assert.doesNotMatch(html,/data-kosell-op="rent"/);assert.doesNotMatch(html,/<img src=x>/);assert.match(source,/kosellAction\('preview'/);assert.match(source,/kosellUi\.preview\.token/);});
test('New plugin is legendary and assets load before app; existing cover layout stays unchanged',()=>{const rarity=readFileSync(new URL('./plugin-rarity.js',import.meta.url),'utf8'),page=readFileSync(new URL('./plugin-page.js',import.meta.url),'utf8'),html=readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.match(rarity,/'zetslay.kosell-rent':'legendary'/);assert.match(page,/typeof kosellRentMarkup/);assert.ok(html.indexOf('src="kosell-rent.js')<html.indexOf('src="app.js'));assert.ok(!source.includes('<figure'));assert.ok(!source.includes('data-cover-plugin'));});
test('Advanced controls, offer preview and costs are visible with every financial automation opt-in',async()=>{const f=app();f.status.analytics={currencies:{RUB:{orderAmountMinor:10000,refundedAmountMinor:0,providerCostMinor:2000,marginBeforeFeesMinor:8000,uncertain:1}},days:[],games:[]};f.status.offerJobs=[{id:'j',status:'unknown',productName:'<script>x</script>',hours:12,priceMinor:2904,currency:'RUB'}];await f.run('loadKosellStatus()');const html=f.run('kosellRentMarkup({installed:true})');assert.match(html,/name="autoHideStock"/);assert.match(html,/name="buyerExtensionEnabled"/);assert.match(html,/data-kosell-offers/);assert.match(html,/data-kosell-offer-resolve/);assert.match(html,/Разница до комиссий/);assert.doesNotMatch(html,/<script>x/);assert.doesNotMatch(html,/name="reviewBonusEnabled" checked/);assert.doesNotMatch(html,/name="manageOffers" checked/);});
test('Closing an offer asks before mutating FunPay and requires a second confirmation',async()=>{const f=app();await f.run('loadKosellStatus()');const el={dataset:{kosellCloseJob:'job-123'}};await f.handlers.click({target:{closest:()=>el}});assert.equal(f.calls.filter(c=>c.options?.method==='POST').length,0);assert.equal(f.run('kosellUi.confirmAction.path'),'offer-cancel');await f.handlers.click({target:{closest:()=>({dataset:{kosellAction:'confirm-action'}})}});assert.equal(f.calls.find(c=>c.path.endsWith('/offer-cancel')).options.body.confirm,true);});
test('Offer creation preview is separate from purchase and accepts a bounded explicit duration list',async()=>{const f=app();await f.run('loadKosellStatus()');const form={matches:s=>s.includes('data-kosell-offers'),values:new Map([['templateLotId','321'],['productId','1'],['durations','1, 12, 24']])};await f.handlers.submit({target:form,preventDefault(){}});const req=f.calls.find(c=>c.path.endsWith('/offer-preview'));assert.deepEqual(Array.from(req.options.body.durations),[1,12,24]);assert.equal(req.options.body.activate,false);assert.ok(!f.calls.some(c=>c.path.endsWith('/offer-confirm')));});
