/* Kosell keys go to a private API POST only. Nothing is stored in localStorage. */
const kosellUi={session:null,status:null,loading:false,busy:false,error:'',products:[],preview:null,provider:null,offerPreview:null,confirmAction:null};
const kosellLabels={ignored:'Старый заказ пропущен',discovering:'Читаем заказ',unmatched:'Лот не привязан',queued:'Ожидает подтверждения',purchasing:'Создаём аренду',purchase_unknown:'Покупка требует проверки',rented:'Аренда создана · выдача ожидается',sending:'Отправляем данные',delivered:'Выдано покупателю',delivery_unknown:'Доставка требует проверки',failed:'Поставщик отклонил операцию',cancelled:'Отменено',expired:'Срок истёк',terminated:'Завершено владельцем'};
const kosellMoney=(minor,currency)=>`${(Number(minor||0)/100).toFixed(2)} ${escapeHtml(currency)}`;
const kosellAdvancedDefaults={manageOffers:false,salesPaused:false,autoHideStock:false,autoHideBalance:false,minimumBalanceMinor:0,autoReprice:false,markupPercent:20,priceIntervalMinutes:15,inventoryIntervalMinutes:5,warningMinutes:30,notifyOwner:true,buyerPasswordEnabled:false,buyerLogoutEnabled:false,buyerExtensionEnabled:false,extensionMarkupPercent:20,extensionLifetimeMinutes:20,reviewBonusEnabled:false,reviewBonusHours:2,reviewBonusMinStars:5,warningTemplate:'$username, аренда $game заканчивается через $minutes мин. До $expires.',extensionTemplate:'Продление $game на $hours ч: $price. Оплата: $link. Ссылка на $minutes мин.',bonusTemplate:'$username, спасибо за отзыв! Добавлено $hours ч. До $expires.',offerTitleTemplate:'$game · аренда $hours ч',offerDescriptionTemplate:'Аренда $game на $hours ч. Данные после оплаты.',extensionOfferTitleTemplate:'$game · продление $hours ч',extensionOfferDescriptionTemplate:'Продление $game на $hours ч для заказа #$order_id.'};
function kosellAutomationFields(input){const c={...kosellAdvancedDefaults,...input};
  const check=(key,text)=>`<label><input type="checkbox" name="${key}" ${c[key]?'checked':''}>${text}</label>`;
  const number=(key,text,min,max)=>`<label>${text}<input type="number" name="${key}" min="${min}" max="${max}" value="${c[key]}" required></label>`;
  const template=(key,text)=>`<label>${text}<textarea name="${key}" rows="3" maxlength="${key.includes('Title')?150:700}" required>${escapeHtml(c[key])}</textarea></label>`;
  return `<details class="kosell-settings-group"><summary>Лоты, наличие и цены<span>Автоматизация ассортимента</span></summary><div class="kosell-switches">${check('manageOffers','Разрешить управление привязанными лотами FunPay')}${check('salesPaused','Приостановить продажи всех привязанных лотов')}${check('autoHideStock','Скрывать при отсутствии аккаунтов Kosell')}${check('autoHideBalance','Скрывать при недостаточном балансе')}${check('autoReprice','Пересчитывать цену по серверной себестоимости и наценке')}</div><div class="kosell-fields">${number('markupPercent','Наценка, %',0,1000)}<label>Минимальный баланс (${escapeHtml(c.currency||'RUB')})<input name="minimumBalance" type="text" inputmode="decimal" value="${(c.minimumBalanceMinor/100).toFixed(2)}" required></label>${number('inventoryIntervalMinutes','Проверка наличия: минут',3,1440)}${number('priceIntervalMinutes','Пересчёт цены: минут',5,1440)}</div><p class="kosell-hint">Возвращаются только лоты, скрытые самим плагином. Ручные изменения останавливают управление до вашей проверки. Наценка не включает комиссию FunPay.</p></details>
  <details class="kosell-settings-group"><summary>Покупатель и срок аренды<span>Команды и уведомления</span></summary><div class="kosell-switches">${check('buyerPasswordEnabled','Разрешить !пароль с подтверждением покупателя')}${check('buyerLogoutEnabled','Разрешить !кик с подтверждением покупателя')}${check('buyerExtensionEnabled','Разрешить !продление ЧАСЫ НОМЕР_ЗАКАЗА с оплатой личного лота')}${check('notifyOwner','Присылать продавцу события Kosell в Telegram')}</div><div class="kosell-fields">${number('warningMinutes','Предупреждать за: минут (0 — выключено)',0,1440)}${number('extensionMarkupPercent','Наценка продления, %',0,1000)}${number('extensionLifetimeMinutes','Личный лот действует: минут',5,120)}</div><p class="kosell-hint">Для платного продления требуется разрешение управления лотами. Часы добавляются после оплаты тем же покупателем. При выключении плагина сначала закройте временные предложения.</p>${template('warningTemplate','Предупреждение об окончании')}${template('extensionTemplate','Предложение платного продления')}</details>
  <details class="kosell-settings-group"><summary>Бонус за отзыв<span>Дополнительные часы за ваш счёт</span></summary><div class="kosell-switches">${check('reviewBonusEnabled','Начислять бонус один раз после подтверждения заказа и проверки оценки')}</div><div class="kosell-fields">${number('reviewBonusHours','Бонусных часов',1,720)}${number('reviewBonusMinStars','Минимальная оценка',1,5)}</div>${template('bonusTemplate','Сообщение о начислении')}<p class="kosell-hint">Статус и оценка проверяются повторно перед списанием. Бонус оплачивается из вашего баланса Kosell в пределах лимита; неопределённый результат блокирует повтор.</p></details>
  <details class="kosell-settings-group"><summary>Тексты новых предложений<span>Шаблоны лотов FunPay</span></summary>${template('offerTitleTemplate','Название аренды')}${template('offerDescriptionTemplate','Описание аренды')}${template('extensionOfferTitleTemplate','Название личного продления')}${template('extensionOfferDescriptionTemplate','Описание личного продления')}<p class="kosell-hint">Переменные: $game · $hours · $order_id. Категория, параметры и изображения наследуются от выбранного вами шаблона.</p></details>`;
}
function kosellOperationsMarkup(s){const currencies=Object.entries(s.analytics?.currencies||{}),jobs=s.offerJobs||[];
  return `<section><div class="kosell-section-title"><h3>Учёт операций</h3><span>4</span></div><div class="kosell-metrics">${currencies.map(([c,r])=>`<article><span>Сумма заказов · ${escapeHtml(c)}</span><strong>${kosellMoney(r.orderAmountMinor,c)}</strong><small>Возвращено ${kosellMoney(r.refundedAmountMinor,c)}</small></article><article><span>Расходы Kosell · ${escapeHtml(c)}</span><strong>${kosellMoney(r.providerCostMinor,c)}</strong><small>Покупки, продления и бонусы</small></article><article><span>Разница до комиссий · ${escapeHtml(c)}</span><strong>${kosellMoney(r.marginBeforeFeesMinor,c)}</strong><small>Неопределённых операций: ${r.uncertain}${r.partialRefunds?' · частичные возвраты требуют проверки':''}</small></article>`).join('')||'<p>Учёт появится после первых обработанных заказов.</p>'}</div><p class="kosell-hint">Комиссии FunPay не включены. Отчёт охватывает только заказы этого плагина; неопределённые списания не считаются подтверждёнными расходами.</p><details class="kosell-provider"><summary>Дни и игры</summary>${(s.analytics?.days||[]).map(d=>`<p>${escapeHtml(d.date)} · ${Object.entries(d.totals).map(([c,n])=>kosellMoney(n,c)).join(' / ')}</p>`).join('')}${(s.analytics?.games||[]).map(g=>`<p>${escapeHtml(g.name)} · ${g.orders} заказов · ${g.hours} ч</p>`).join('')}</details></section>
  <section><div class="kosell-section-title"><h3>Создать предложения по шаблону</h3><span>5</span></div><p>Выберите собственный лот нужной игры. Сервис сохранит его категорию, параметры и изображения, создаст предложения на выбранные сроки и свяжет их с Kosell.</p><form data-kosell-offers><fieldset ${kosellUi.busy?'disabled':''}><div class="kosell-fields"><label>ID своего лота-шаблона<input name="templateLotId" inputmode="numeric" pattern="[1-9][0-9]{0,19}" required></label><label>Игра Kosell<select name="productId" required><option value="">Сначала загрузите игры выше</option>${kosellUi.products.map(r=>`<option value="${r.id}">${escapeHtml(r.name)}</option>`).join('')}</select></label><label>Сроки в часах через запятую<input name="durations" required value="1, 12, 24" maxlength="100"></label><label class="kosell-switches"><input name="activate" type="checkbox">Активировать новые предложения после проверки</label></div><button type="submit" class="button button--ghost">Подготовить сводку создания</button></fieldset></form><div class="kosell-list">${jobs.map(j=>`<article><div><strong>${escapeHtml(j.productName)} · ${j.hours} ч${j.extensionFor?' · продление #'+escapeHtml(j.extensionFor):''}</strong><p>${escapeHtml({queued:'В очереди',creating:'Создание',created:'Создан выключенным',active:'Активен',activating:'Активация',unknown:'Требует ручной проверки',expired:'Срок предложения истёк',consumed:'Использован',cancelled:'Закрыт',failed:'Ошибка'}[j.status]||j.status)} · ${kosellMoney(j.priceMinor,j.currency)}</p>${j.lotId?`<a href="https://funpay.com/lots/offer?id=${escapeHtml(j.lotId)}" target="_blank" rel="noopener noreferrer">Лот #${escapeHtml(j.lotId)}</a>`:''}${j.code?`<p>${escapeHtml(j.code)}</p>`:''}</div>${['queued','created','active','unknown'].includes(j.status)?`<button class="button button--ghost" data-kosell-close-job="${escapeHtml(j.id)}">Закрыть предложение</button>`:''}${j.status==='unknown'?`<form data-kosell-offer-resolve data-job-id="${escapeHtml(j.id)}"><label>ID лота, создание которого вы проверили на FunPay<input name="lotId" inputmode="numeric" value="${escapeHtml(j.lotId||'')}" required></label><label class="kosell-switches"><input type="checkbox" name="confirm" required>Я проверил результат создания</label><button class="button button--ghost" type="submit">Проверить и связать лот</button></form>`:''}</article>`).join('')}</div></section>`;
}
function kosellConfirmationMarkup(){const p=kosellUi.offerPreview,q=kosellUi.confirmAction;
  if(p)return `<section class="kosell-preview" role="dialog" aria-labelledby="kosell-offer-title"><h3 id="kosell-offer-title">Создание новых лотов</h3><p>Шаблон #${escapeHtml(p.templateLotId)} · ${p.activate?'с последующей активацией':'выключенные предложения'}</p>${p.items.map(i=>`<p>${escapeHtml(i.productName)} · ${i.hours} ч · ${kosellMoney(i.priceMinor,p.currency)}</p>`).join('')}<blockquote>${escapeHtml(p.warning)}</blockquote><div class="kosell-buttons"><button class="button button--primary" data-kosell-action="offer-confirm">Подтвердить создание</button><button class="button button--ghost" data-kosell-action="cancel-preview">Отмена</button></div></section>`;
  if(q)return `<section class="kosell-preview" role="dialog" aria-labelledby="kosell-action-title"><h3 id="kosell-action-title">Подтвердите изменение</h3><p>${escapeHtml(q.message)}</p><div class="kosell-buttons"><button class="button button--primary" data-kosell-action="confirm-action">Подтвердить</button><button class="button button--ghost" data-kosell-action="cancel-preview">Отмена</button></div></section>`;
  return '';
}
function resetKosellUi(){Object.assign(kosellUi,{session:authState.token,status:null,loading:false,busy:false,error:'',products:[],preview:null,provider:null,offerPreview:null,confirmAction:null});}
function kosellRentMarkup(plugin){
  if(!plugin.installed)return `<section class="plugin-page-panel kosell-intro"><span class="kosell-star" aria-hidden="true">✧</span><h2>Заказ → аренда → довольный покупатель</h2><p>Установите плагин, чтобы подключить Kosell и настроить выдачу. API-ключ вводится только здесь, в кабинете.</p></section>`;
  if(kosellUi.session!==authState.token)resetKosellUi();
  if(!kosellUi.status&&!kosellUi.loading&&!kosellUi.error)queueMicrotask(()=>loadKosellStatus());
  const s=kosellUi.status;
  if(!s)return `<section class="plugin-page-panel" data-kosell-panel><h2>Kosell Rent</h2><p role="status">${escapeHtml(kosellUi.error||'Загружаем подключение…')}</p><button class="button button--ghost" data-kosell-action="status">Повторить загрузку</button></section>`;
  const c=s.config||{},account=kosellUi.provider?.providerAccount||s.providerAccount,p=kosellUi.preview;
  return `<section class="plugin-page-panel kosell-panel" data-kosell-panel aria-labelledby="kosell-title"><header class="kosell-heading"><div><span class="kosell-caption">Аренда игровых аккаунтов</span><h2 id="kosell-title">Kosell Rent <span>✧</span></h2><p>Игра, срок и правила выдачи — под вашим контролем.</p></div><button class="button button--ghost" type="button" data-kosell-action="status" ${kosellUi.busy?'disabled':''}>Обновить</button></header>
  <div class="kosell-metrics"><article><span>Подключение Kosell</span><strong>${s.keyConfigured?'Ключ сохранён':'Нужно настроить'}</strong><small>${escapeHtml(account?.username||'API-ключ вводится ниже')}</small></article><article><span>Баланс поставщика</span><strong>${account?kosellMoney(account.balanceRubMinor,'RUB'):'—'}</strong><small>${account?kosellMoney(account.balanceUsdMinor,'USD'):'Нажмите «Проверить баланс»'}</small></article><article><span>Автоматическая выдача</span><strong>${c.automatic?'Включена':'Выключена'}</strong><small>${s.workerEnabled&&s.purchaseEnabled&&s.deliveryEnabled?'Серверный исполнитель готов':'Исполнитель не включён на сервере'}</small></article></div>
  ${s.lifecycleError?'<p class="kosell-hint" role="status">Проверка дополнительных функций не завершилась. Обновите состояние и проверьте доступность Kosell.</p>':''}${s.offerSweep?`<p class="kosell-hint">Проверка лотов: ${s.offerSweep.processed} из ${s.offerSweep.total}. Остальные проверятся на следующих проходах.</p>`:''}
  <p class="kosell-feedback" role="status">${escapeHtml(kosellUi.error)}</p>
  ${p?`<section class="kosell-preview" role="dialog" aria-labelledby="kosell-preview-title"><h3 id="kosell-preview-title">Проверьте действие перед запуском</h3><p>Заказ <strong>#${escapeHtml(p.orderId)}</strong> · ${escapeHtml(p.productName)} · ${p.hours} ч</p><p>Действие: <strong>${escapeHtml({rent:'Создать аренду',extend:'Продлить аренду',terminate:'Завершить без возврата','rotate-password':'Сменить пароль','full-logout':'Закрыть Steam-сессии',deliver:'Повторно выдать данные'}[p.operation]||p.operation)}</strong></p><p>Расход: <strong>${kosellMoney(p.costMinor,p.currency)}</strong></p><blockquote>${escapeHtml(p.warning)}</blockquote><p>Подтверждение действует 5 минут. Цена проверяется повторно.</p><div class="kosell-buttons"><button class="button button--primary" data-kosell-action="confirm" ${kosellUi.busy?'disabled':''}>Подтвердить действие</button><button class="button button--ghost" data-kosell-action="cancel-preview">Отмена</button></div></section>`:''}
  ${kosellConfirmationMarkup()}
  <form data-kosell-settings><fieldset ${kosellUi.busy?'disabled':''}><div class="kosell-section-title"><h3>Подключение и правила расходов</h3><span>1</span></div><div class="kosell-fields"><label>API-ключ Kosell<input type="password" name="apiKey" maxlength="512" autocomplete="off" spellcheck="false" placeholder="${s.keyConfigured?'Уже сохранён. Оставьте пустым':'Вставьте API-ключ'}"></label><label>Валюта<select name="currency"><option value="RUB" ${c.currency==='RUB'?'selected':''}>RUB · рубли</option><option value="USD" ${c.currency==='USD'?'selected':''}>USD · доллары</option></select></label><label>Лимит одной покупки / продления<input name="maxSpend" type="text" inputmode="decimal" required maxlength="12" value="${(c.maxSpendMinor/100).toFixed(2)}"></label></div><div class="kosell-switches"><label><input type="checkbox" name="automatic" ${c.automatic?'checked':''}> Автоматически покупать и выдавать по новым оплаченным заказам</label><label><input type="checkbox" name="guardEnabled" ${c.guardEnabled?'checked':''}> Выдавать Steam Guard по команде покупателя</label></div><label>Сообщение с данными аккаунта<textarea name="deliveryTemplate" maxlength="700" rows="6" required>${escapeHtml(c.deliveryTemplate)}</textarea></label><p class="kosell-hint">Переменные: $username · $game · $login · $password · $expires · $order_id. Логин и пароль обязательны. Валюта заказа FunPay должна совпадать с выбранной валютой; расходы не могут превышать сумму заказа.</p>${kosellAutomationFields(c)}<div class="kosell-buttons"><button class="button button--primary" type="submit">Сохранить настройки</button><button class="button button--ghost" type="button" data-kosell-action="refresh">Проверить баланс и аренды</button></div></fieldset></form>
  <section class="kosell-mapping"><div class="kosell-section-title"><h3>Привязки лотов</h3><span>2</span></div><p>Обычный лот вашего магазина → продукт Kosell → часы за одну единицу товара. Переоценка и скрытие включаются отдельно в настройках.</p><div class="kosell-buttons"><input data-kosell-search aria-label="Поиск игры Kosell" placeholder="Название игры"><button class="button button--ghost" type="button" data-kosell-action="products" ${kosellUi.busy?'disabled':''}>Загрузить игры</button></div><form data-kosell-mapping><fieldset ${kosellUi.busy?'disabled':''}><div class="kosell-fields"><label>ID лота FunPay<input name="lotId" inputmode="numeric" pattern="[1-9][0-9]{0,19}" required placeholder="Из ссылки offer?id=…"></label><label>ID обычного раздела<input name="nodeId" inputmode="numeric" pattern="[1-9][0-9]{0,19}" required placeholder="Из ссылки /lots/123/"> </label><label>Продукт Kosell<select name="productId" required><option value="">Выберите игру</option>${kosellUi.products.map(r=>`<option value="${r.id}">${escapeHtml(r.name)} · доступно ${r.availableAccounts}</option>`).join('')}</select></label><label>Часов за единицу<input type="number" name="hours" min="1" max="720" value="1" required></label><label>Индивидуальная наценка, % (пусто — общая)<input type="number" name="markupPercent" min="0" max="1000"></label></div><button class="button button--primary" type="submit">Проверить лот и сохранить привязку</button></fieldset></form><div class="kosell-list">${s.mappings.map(m=>`<article><div><strong>${escapeHtml(m.title||'#'+m.lotId)}</strong><p>${escapeHtml(m.productName)} · ${m.hours} ч · лот #${escapeHtml(m.lotId)}</p>${m.control?`<p>Управление: ${escapeHtml(m.control.state)}${m.control.reasons?.length?" · "+escapeHtml(m.control.reasons.join(", ")):""}${m.control.error?" · "+escapeHtml(m.control.error):""}</p><button type="button" class="button button--ghost" data-kosell-control-reset="${escapeHtml(m.lotId)}">Принять текущее состояние лота</button>`:""}</div><button type="button" class="button button--ghost" data-kosell-remove="${escapeHtml(m.lotId)}" data-node-id="${escapeHtml(m.nodeId)}" ${kosellUi.busy?'disabled':''}>Убрать привязку</button></article>`).join('')||'<p>Привязок пока нет. После сохранения начинайте с нового тестового заказа.</p>'}</div></section>
  <section><div class="kosell-section-title"><h3>Заказы и аренды</h3><span>3</span></div><p class="kosell-hint">Неизвестный результат запрещает повторную покупку. «Повторно выдать» требует вашего подтверждения и не создаёт аренду.</p><div class="kosell-list">${s.tasks.filter(t=>!['ignored','unmatched'].includes(t.status)).map(t=>`<article class="kosell-job"><div><strong>#${escapeHtml(t.orderId)} · ${escapeHtml(t.productName||'Чтение заказа')}</strong><p class="kosell-job-status">${escapeHtml(kosellLabels[t.status]||t.status)}</p><small>${t.rentalUid?'UID '+escapeHtml(t.rentalUid)+' · ':''}${t.hours?t.hours+' ч':''}${t.expiresAt?' · до '+escapeHtml(new Date(t.expiresAt).toLocaleString('ru-RU')):''}</small>${t.code?`<p>${escapeHtml(t.code)}</p>`:''}${t.operation?`<p>Последняя операция: ${escapeHtml(t.operation.type)} · ${escapeHtml(t.operation.status)}</p>`:''}</div><div class="kosell-job-actions">${['queued','failed'].includes(t.status)?`<button class="button button--primary" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="rent">Проверить покупку</button><button class="button button--ghost" data-kosell-task-cancel="${escapeHtml(t.orderId)}">Отменить задачу</button>`:''}${t.rentalUid&&['delivered','rented','delivery_unknown'].includes(t.status)?`<input type="number" data-kosell-hours min="1" max="720" value="1" aria-label="Часы продления"><button class="button button--ghost" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="extend">Продлить</button><button class="button button--ghost" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="rotate-password">Сменить пароль</button><button class="button button--ghost" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="full-logout">Закрыть сессии</button><button class="button button--ghost" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="deliver">Повторно выдать</button><button class="button button--ghost kosell-danger" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="terminate">Завершить аренду</button>`:''}</div>${t.status==='purchase_unknown'?`<form data-kosell-reconcile data-order-id="${escapeHtml(t.orderId)}"><label>UID покупки, которую вы проверили в Kosell<input name="rentalUid" required maxlength="128" placeholder="Нажмите «Проверить баланс и аренды» для списка UID"></label><label class="kosell-switches"><input name="confirm" type="checkbox" required> Я проверил, что эта аренда куплена для данного заказа</label><button class="button button--ghost" type="submit">Проверить и связать существующую аренду</button></form>`:''}</article>`).join('')||'<p>Новые заказы появятся после фонового чтения. Заказы до включения плагина не покупаются автоматически.</p>'}</div></section>
  ${kosellOperationsMarkup(s)}
  ${kosellUi.provider?`<details class="kosell-provider"><summary>Активные аренды в аккаунте Kosell (${kosellUi.provider.active.length})</summary>${kosellUi.provider.active.map(r=>`<p><strong>${escapeHtml(r.productName)}</strong> · UID <code>${escapeHtml(r.rentalUid)}</code> · ${r.hours} ч · осталось ${Math.floor(r.remainingSeconds/60)} мин</p>`).join('')}</details>`:''}
  <aside class="kosell-note"><strong>Ключи остаются в кабинете</strong><p>Настройки и очередь: <code>/kosell</code> в вашем рабочем боте. Steam Guard: <code>!steamcode НОМЕР_ЗАКАЗА</code> в чате FunPay. Ключ Kosell, Golden Key и прокси туда не отправляйте.</p></aside></section>`;
}
async function loadKosellStatus(){if(!authState.token||kosellUi.loading)return;if(kosellUi.session!==authState.token)resetKosellUi();const session=authState.token;kosellUi.loading=true;try{const s=await apiRequest('/api/v1/plugins/kosell-rent/status',{authenticated:true});if(authState.token===session){kosellUi.status=s;kosellUi.error='';}}catch(e){if(authState.token===session)kosellUi.error=humanError(e);}finally{if(authState.token===session){kosellUi.loading=false;renderPluginPage();}}}
async function kosellAction(path,body){if(kosellUi.busy)return;const session=authState.token;kosellUi.busy=true;renderPluginPage();try{const result=await apiRequest('/api/v1/plugins/kosell-rent/'+path,{method:'POST',authenticated:true,...(body===undefined?{}:{body})});if(authState.token!==session)return;if(path==='preview')kosellUi.preview=result;else if(path==='offer-preview')kosellUi.offerPreview=result;else{kosellUi.preview=null;kosellUi.offerPreview=null;kosellUi.confirmAction=null;if(path==='refresh')kosellUi.provider=result;await loadKosellStatus();kosellUi.error='Действие обработано. Проверьте состояние задачи.';}}catch(e){if(authState.token===session)kosellUi.error=humanError(e);}finally{if(authState.token===session){kosellUi.busy=false;renderPluginPage();}}}
document.addEventListener('submit',async event=>{const form=event.target;if(!form.matches('[data-kosell-settings],[data-kosell-mapping],[data-kosell-reconcile],[data-kosell-offers],[data-kosell-offer-resolve]'))return;event.preventDefault();if(kosellUi.busy)return;const f=new FormData(form);
  if(form.matches('[data-kosell-settings]')){const value=String(f.get('maxSpend')).replace(',','.');if(!/^\d{1,7}(?:\.\d{1,2})?$/.test(value)){kosellUi.error='Лимит: положительная сумма с двумя знаками после запятой';renderPluginPage();return;}const body={config:{...kosellAdvancedDefaults,...kosellUi.status.config,automatic:f.has('automatic'),guardEnabled:f.has('guardEnabled'),currency:String(f.get('currency')),maxSpendMinor:Math.round(Number(value)*100),deliveryTemplate:String(f.get('deliveryTemplate'))}};for(const k of ['manageOffers','salesPaused','autoHideStock','autoHideBalance','autoReprice','notifyOwner','buyerPasswordEnabled','buyerLogoutEnabled','buyerExtensionEnabled','reviewBonusEnabled'])body.config[k]=f.has(k);for(const k of ['markupPercent','priceIntervalMinutes','inventoryIntervalMinutes','warningMinutes','extensionMarkupPercent','extensionLifetimeMinutes','reviewBonusHours','reviewBonusMinStars'])if(f.has(k))body.config[k]=Number(f.get(k));for(const k of ['warningTemplate','extensionTemplate','bonusTemplate','offerTitleTemplate','offerDescriptionTemplate','extensionOfferTitleTemplate','extensionOfferDescriptionTemplate'])if(f.has(k))body.config[k]=String(f.get(k));if(f.has('minimumBalance')){const n=String(f.get('minimumBalance')).replace(',','.');if(!/^\d{1,7}(?:\.\d{1,2})?$/.test(n)){kosellUi.error='Проверьте минимальный баланс';renderPluginPage();return;}body.config.minimumBalanceMinor=Math.round(Number(n)*100);} const key=String(f.get('apiKey')||'');if(key)body.apiKey=key;form.querySelector('[name=apiKey]').value='';await kosellAction('settings',body);}
  else if(form.matches('[data-kosell-mapping]'))await kosellAction('mapping',{lotId:String(f.get('lotId')),nodeId:String(f.get('nodeId')),productId:Number(f.get('productId')),hours:Number(f.get('hours')),...(f.get('markupPercent')?{markupPercent:Number(f.get('markupPercent'))}:{})});
  else if(form.matches('[data-kosell-offers]')){const raw=String(f.get('durations'));if(!/^\s*\d{1,3}(?:\s*,\s*\d{1,3}){0,11}\s*$/.test(raw)){kosellUi.error='До 12 целых сроков через запятую';renderPluginPage();return;}await kosellAction('offer-preview',{templateLotId:String(f.get('templateLotId')),productId:Number(f.get('productId')),durations:raw.split(',').map(Number),activate:f.has('activate')});}
  else if(form.matches('[data-kosell-offer-resolve]'))await kosellAction('offer-resolve',{jobId:form.dataset.jobId,lotId:String(f.get('lotId')),confirm:f.has('confirm')});
  else await kosellAction('reconcile',{orderId:form.dataset.orderId,rentalUid:String(f.get('rentalUid')),confirm:f.has('confirm')});
});
document.addEventListener('click',async event=>{const el=event.target.closest('[data-kosell-action],[data-kosell-op],[data-kosell-remove],[data-kosell-close-job],[data-kosell-control-reset],[data-kosell-task-cancel]');if(!el||kosellUi.busy)return;const action=el.dataset.kosellAction;
  if(action==='status')await loadKosellStatus();else if(action==='cancel-preview'){kosellUi.preview=null;kosellUi.offerPreview=null;kosellUi.confirmAction=null;renderPluginPage();}else if(action==='refresh')await kosellAction('refresh');else if(action==='confirm'){if(kosellUi.preview){const token=kosellUi.preview.token;kosellUi.preview=null;await kosellAction('confirm',{token});}}
  else if(action==='offer-confirm'&&kosellUi.offerPreview)await kosellAction('offer-confirm',{token:kosellUi.offerPreview.token});
  else if(action==='confirm-action'&&kosellUi.confirmAction){const q=kosellUi.confirmAction;kosellUi.confirmAction=null;await kosellAction(q.path,q.body);}
  else if(el.dataset.kosellCloseJob||el.dataset.kosellControlReset||el.dataset.kosellTaskCancel){kosellUi.confirmAction=el.dataset.kosellCloseJob?{path:'offer-cancel',body:{jobId:el.dataset.kosellCloseJob,confirm:true},message:'Предложение будет выключено на FunPay. Это не завершает аренду и не возвращает деньги.'}:el.dataset.kosellControlReset?{path:'offer-control-reset',body:{lotId:el.dataset.kosellControlReset,confirm:true},message:'Принять текущие настройки лота и разрешить дальнейшее управление. Выключенный вручную лот автоматически включаться не будет.'}:{path:'task-cancel',body:{orderId:el.dataset.kosellTaskCancel,confirm:true},message:'Остановить покупку по этой задаче. Заказ на FunPay не отменяется; деньги не возвращаются.'};renderPluginPage();}
  else if(action==='products'){const search=document.querySelector('[data-kosell-search]')?.value||'',session=authState.token;kosellUi.busy=true;try{const rows=await apiRequest('/api/v1/plugins/kosell-rent/products?search='+encodeURIComponent(search),{authenticated:true});if(session===authState.token){kosellUi.products=rows;kosellUi.error='Игры загружены. Выберите продукт в привязке.';}}catch(e){if(session===authState.token)kosellUi.error=humanError(e);}finally{if(session===authState.token){kosellUi.busy=false;renderPluginPage();}}}
  else if(el.dataset.kosellOp)await kosellAction('preview',{orderId:el.dataset.kosellOrder,operation:el.dataset.kosellOp,...(el.dataset.kosellOp==='extend'?{hours:Number(el.closest('.kosell-job').querySelector('[data-kosell-hours]').value)}:{})});
  else if(el.dataset.kosellRemove)await kosellAction('mapping',{lotId:el.dataset.kosellRemove,nodeId:el.dataset.nodeId,remove:true});
});
