/* Kosell keys go to a private API POST only. Nothing is stored in localStorage. */
const kosellUi={session:null,status:null,loading:false,busy:false,error:'',products:[],preview:null,provider:null};
const kosellLabels={ignored:'Старый заказ пропущен',discovering:'Читаем заказ',unmatched:'Лот не привязан',queued:'Ожидает подтверждения',purchasing:'Создаём аренду',purchase_unknown:'Покупка требует проверки',rented:'Аренда создана · выдача ожидается',sending:'Отправляем данные',delivered:'Выдано покупателю',delivery_unknown:'Доставка требует проверки',failed:'Поставщик отклонил операцию',cancelled:'Отменено',expired:'Срок истёк',terminated:'Завершено владельцем'};
const kosellMoney=(minor,currency)=>`${(Number(minor||0)/100).toFixed(2)} ${escapeHtml(currency)}`;
function resetKosellUi(){Object.assign(kosellUi,{session:authState.token,status:null,loading:false,busy:false,error:'',products:[],preview:null,provider:null});}
function kosellRentMarkup(plugin){
  if(!plugin.installed)return `<section class="plugin-page-panel kosell-intro"><span class="kosell-star" aria-hidden="true">✧</span><h2>Заказ → аренда → довольный покупатель</h2><p>Установите плагин, чтобы подключить Kosell и настроить выдачу. API-ключ вводится только здесь, в кабинете.</p></section>`;
  if(kosellUi.session!==authState.token)resetKosellUi();
  if(!kosellUi.status&&!kosellUi.loading&&!kosellUi.error)queueMicrotask(()=>loadKosellStatus());
  const s=kosellUi.status;
  if(!s)return `<section class="plugin-page-panel" data-kosell-panel><h2>Kosell Rent</h2><p role="status">${escapeHtml(kosellUi.error||'Загружаем подключение…')}</p><button class="button button--ghost" data-kosell-action="status">Повторить загрузку</button></section>`;
  const c=s.config||{},account=kosellUi.provider?.providerAccount||s.providerAccount,p=kosellUi.preview;
  return `<section class="plugin-page-panel kosell-panel" data-kosell-panel aria-labelledby="kosell-title"><header class="kosell-heading"><div><span class="kosell-caption">Аренда игровых аккаунтов</span><h2 id="kosell-title">Kosell Rent <span>✧</span></h2><p>Игра, срок и правила выдачи — под вашим контролем.</p></div><button class="button button--ghost" type="button" data-kosell-action="status" ${kosellUi.busy?'disabled':''}>Обновить</button></header>
  <div class="kosell-metrics"><article><span>Подключение Kosell</span><strong>${s.keyConfigured?'Ключ сохранён':'Нужно настроить'}</strong><small>${escapeHtml(account?.username||'API-ключ вводится ниже')}</small></article><article><span>Баланс поставщика</span><strong>${account?kosellMoney(account.balanceRubMinor,'RUB'):'—'}</strong><small>${account?kosellMoney(account.balanceUsdMinor,'USD'):'Нажмите «Проверить баланс»'}</small></article><article><span>Автоматическая выдача</span><strong>${c.automatic?'Включена':'Выключена'}</strong><small>${s.workerEnabled&&s.purchaseEnabled&&s.deliveryEnabled?'Серверный исполнитель готов':'Исполнитель не включён на сервере'}</small></article></div>
  <p class="kosell-feedback" role="status">${escapeHtml(kosellUi.error)}</p>
  ${p?`<section class="kosell-preview" role="dialog" aria-labelledby="kosell-preview-title"><h3 id="kosell-preview-title">Проверьте действие перед запуском</h3><p>Заказ <strong>#${escapeHtml(p.orderId)}</strong> · ${escapeHtml(p.productName)} · ${p.hours} ч</p><p>Действие: <strong>${escapeHtml({rent:'Создать аренду',extend:'Продлить аренду',terminate:'Завершить без возврата','rotate-password':'Сменить пароль','full-logout':'Закрыть Steam-сессии',deliver:'Повторно выдать данные'}[p.operation]||p.operation)}</strong></p><p>Расход: <strong>${kosellMoney(p.costMinor,p.currency)}</strong></p><blockquote>${escapeHtml(p.warning)}</blockquote><p>Подтверждение действует 5 минут. Цена проверяется повторно.</p><div class="kosell-buttons"><button class="button button--primary" data-kosell-action="confirm" ${kosellUi.busy?'disabled':''}>Подтвердить действие</button><button class="button button--ghost" data-kosell-action="cancel-preview">Отмена</button></div></section>`:''}
  <form data-kosell-settings><fieldset ${kosellUi.busy?'disabled':''}><div class="kosell-section-title"><h3>Подключение и правила расходов</h3><span>1</span></div><div class="kosell-fields"><label>API-ключ Kosell<input type="password" name="apiKey" maxlength="512" autocomplete="off" spellcheck="false" placeholder="${s.keyConfigured?'Уже сохранён. Оставьте пустым':'Вставьте API-ключ'}"></label><label>Валюта<select name="currency"><option value="RUB" ${c.currency==='RUB'?'selected':''}>RUB · рубли</option><option value="USD" ${c.currency==='USD'?'selected':''}>USD · доллары</option></select></label><label>Лимит одной покупки / продления<input name="maxSpend" type="text" inputmode="decimal" required maxlength="12" value="${(c.maxSpendMinor/100).toFixed(2)}"></label></div><div class="kosell-switches"><label><input type="checkbox" name="automatic" ${c.automatic?'checked':''}> Автоматически покупать и выдавать по новым оплаченным заказам</label><label><input type="checkbox" name="guardEnabled" ${c.guardEnabled?'checked':''}> Выдавать Steam Guard по команде покупателя</label></div><label>Сообщение с данными аккаунта<textarea name="deliveryTemplate" maxlength="700" rows="6" required>${escapeHtml(c.deliveryTemplate)}</textarea></label><p class="kosell-hint">Переменные: $username · $game · $login · $password · $expires · $order_id. Логин и пароль обязательны. Валюта заказа FunPay должна совпадать с выбранной валютой; расходы не могут превышать сумму заказа.</p><div class="kosell-buttons"><button class="button button--primary" type="submit">Сохранить настройки</button><button class="button button--ghost" type="button" data-kosell-action="refresh">Проверить баланс и аренды</button></div></fieldset></form>
  <section class="kosell-mapping"><div class="kosell-section-title"><h3>Привязки лотов</h3><span>2</span></div><p>Обычный лот вашего магазина → продукт Kosell → часы за одну единицу товара. Цена лота не меняется.</p><div class="kosell-buttons"><input data-kosell-search aria-label="Поиск игры Kosell" placeholder="Название игры"><button class="button button--ghost" type="button" data-kosell-action="products" ${kosellUi.busy?'disabled':''}>Загрузить игры</button></div><form data-kosell-mapping><fieldset ${kosellUi.busy?'disabled':''}><div class="kosell-fields"><label>ID лота FunPay<input name="lotId" inputmode="numeric" pattern="[1-9][0-9]{0,19}" required placeholder="Из ссылки offer?id=…"></label><label>ID обычного раздела<input name="nodeId" inputmode="numeric" pattern="[1-9][0-9]{0,19}" required placeholder="Из ссылки /lots/123/"> </label><label>Продукт Kosell<select name="productId" required><option value="">Выберите игру</option>${kosellUi.products.map(r=>`<option value="${r.id}">${escapeHtml(r.name)} · доступно ${r.availableAccounts}</option>`).join('')}</select></label><label>Часов за единицу<input type="number" name="hours" min="1" max="720" value="1" required></label></div><button class="button button--primary" type="submit">Проверить лот и сохранить привязку</button></fieldset></form><div class="kosell-list">${s.mappings.map(m=>`<article><div><strong>${escapeHtml(m.title||'#'+m.lotId)}</strong><p>${escapeHtml(m.productName)} · ${m.hours} ч · лот #${escapeHtml(m.lotId)}</p></div><button type="button" class="button button--ghost" data-kosell-remove="${escapeHtml(m.lotId)}" data-node-id="${escapeHtml(m.nodeId)}" ${kosellUi.busy?'disabled':''}>Убрать привязку</button></article>`).join('')||'<p>Привязок пока нет. После сохранения начинайте с нового тестового заказа.</p>'}</div></section>
  <section><div class="kosell-section-title"><h3>Заказы и аренды</h3><span>3</span></div><p class="kosell-hint">Неизвестный результат запрещает повторную покупку. «Повторно выдать» требует вашего подтверждения и не создаёт аренду.</p><div class="kosell-list">${s.tasks.filter(t=>!['ignored','unmatched'].includes(t.status)).map(t=>`<article class="kosell-job"><div><strong>#${escapeHtml(t.orderId)} · ${escapeHtml(t.productName||'Чтение заказа')}</strong><p class="kosell-job-status">${escapeHtml(kosellLabels[t.status]||t.status)}</p><small>${t.rentalUid?'UID '+escapeHtml(t.rentalUid)+' · ':''}${t.hours?t.hours+' ч':''}${t.expiresAt?' · до '+escapeHtml(new Date(t.expiresAt).toLocaleString('ru-RU')):''}</small>${t.code?`<p>${escapeHtml(t.code)}</p>`:''}${t.operation?`<p>Последняя операция: ${escapeHtml(t.operation.type)} · ${escapeHtml(t.operation.status)}</p>`:''}</div><div class="kosell-job-actions">${['queued','failed'].includes(t.status)?`<button class="button button--primary" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="rent">Проверить покупку</button>`:''}${t.rentalUid&&['delivered','rented','delivery_unknown'].includes(t.status)?`<input type="number" data-kosell-hours min="1" max="720" value="1" aria-label="Часы продления"><button class="button button--ghost" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="extend">Продлить</button><button class="button button--ghost" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="rotate-password">Сменить пароль</button><button class="button button--ghost" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="full-logout">Закрыть сессии</button><button class="button button--ghost" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="deliver">Повторно выдать</button><button class="button button--ghost kosell-danger" data-kosell-order="${escapeHtml(t.orderId)}" data-kosell-op="terminate">Завершить аренду</button>`:''}</div>${t.status==='purchase_unknown'?`<form data-kosell-reconcile data-order-id="${escapeHtml(t.orderId)}"><label>UID покупки, которую вы проверили в Kosell<input name="rentalUid" required maxlength="128" placeholder="Нажмите «Проверить баланс и аренды» для списка UID"></label><label class="kosell-switches"><input name="confirm" type="checkbox" required> Я проверил, что эта аренда куплена для данного заказа</label><button class="button button--ghost" type="submit">Проверить и связать существующую аренду</button></form>`:''}</article>`).join('')||'<p>Новые заказы появятся после фонового чтения. Заказы до включения плагина не покупаются автоматически.</p>'}</div></section>
  ${kosellUi.provider?`<details class="kosell-provider"><summary>Активные аренды в аккаунте Kosell (${kosellUi.provider.active.length})</summary>${kosellUi.provider.active.map(r=>`<p><strong>${escapeHtml(r.productName)}</strong> · UID <code>${escapeHtml(r.rentalUid)}</code> · ${r.hours} ч · осталось ${Math.floor(r.remainingSeconds/60)} мин</p>`).join('')}</details>`:''}
  <aside class="kosell-note"><strong>Ключи остаются в кабинете</strong><p>Настройки и очередь: <code>/kosell</code> в вашем рабочем боте. Steam Guard: <code>!steamcode НОМЕР_ЗАКАЗА</code> в чате FunPay. Ключ Kosell, Golden Key и прокси туда не отправляйте.</p></aside></section>`;
}
async function loadKosellStatus(){if(!authState.token||kosellUi.loading)return;if(kosellUi.session!==authState.token)resetKosellUi();const session=authState.token;kosellUi.loading=true;try{const s=await apiRequest('/api/v1/plugins/kosell-rent/status',{authenticated:true});if(authState.token===session){kosellUi.status=s;kosellUi.error='';}}catch(e){if(authState.token===session)kosellUi.error=humanError(e);}finally{if(authState.token===session){kosellUi.loading=false;renderPluginPage();}}}
async function kosellAction(path,body){if(kosellUi.busy)return;const session=authState.token;kosellUi.busy=true;renderPluginPage();try{const result=await apiRequest('/api/v1/plugins/kosell-rent/'+path,{method:'POST',authenticated:true,...(body===undefined?{}:{body})});if(authState.token!==session)return;if(path==='preview')kosellUi.preview=result;else{kosellUi.preview=null;if(path==='refresh')kosellUi.provider=result;await loadKosellStatus();kosellUi.error='Действие обработано. Проверьте состояние задачи.';}}catch(e){if(authState.token===session)kosellUi.error=humanError(e);}finally{if(authState.token===session){kosellUi.busy=false;renderPluginPage();}}}
document.addEventListener('submit',async event=>{const form=event.target;if(!form.matches('[data-kosell-settings],[data-kosell-mapping],[data-kosell-reconcile]'))return;event.preventDefault();if(kosellUi.busy)return;const f=new FormData(form);
  if(form.matches('[data-kosell-settings]')){const value=String(f.get('maxSpend')).replace(',','.');if(!/^\d{1,7}(?:\.\d{1,2})?$/.test(value)){kosellUi.error='Лимит: положительная сумма с двумя знаками после запятой';renderPluginPage();return;}const body={config:{automatic:f.has('automatic'),guardEnabled:f.has('guardEnabled'),currency:String(f.get('currency')),maxSpendMinor:Math.round(Number(value)*100),deliveryTemplate:String(f.get('deliveryTemplate'))}};const key=String(f.get('apiKey')||'');if(key)body.apiKey=key;form.querySelector('[name=apiKey]').value='';await kosellAction('settings',body);}
  else if(form.matches('[data-kosell-mapping]'))await kosellAction('mapping',{lotId:String(f.get('lotId')),nodeId:String(f.get('nodeId')),productId:Number(f.get('productId')),hours:Number(f.get('hours'))});
  else await kosellAction('reconcile',{orderId:form.dataset.orderId,rentalUid:String(f.get('rentalUid')),confirm:f.has('confirm')});
});
document.addEventListener('click',async event=>{const el=event.target.closest('[data-kosell-action],[data-kosell-op],[data-kosell-remove]');if(!el||kosellUi.busy)return;const action=el.dataset.kosellAction;
  if(action==='status')await loadKosellStatus();else if(action==='cancel-preview'){kosellUi.preview=null;renderPluginPage();}else if(action==='refresh')await kosellAction('refresh');else if(action==='confirm'){if(kosellUi.preview){const token=kosellUi.preview.token;kosellUi.preview=null;await kosellAction('confirm',{token});}}
  else if(action==='products'){const search=document.querySelector('[data-kosell-search]')?.value||'',session=authState.token;kosellUi.busy=true;try{const rows=await apiRequest('/api/v1/plugins/kosell-rent/products?search='+encodeURIComponent(search),{authenticated:true});if(session===authState.token){kosellUi.products=rows;kosellUi.error='Игры загружены. Выберите продукт в привязке.';}}catch(e){if(session===authState.token)kosellUi.error=humanError(e);}finally{if(session===authState.token){kosellUi.busy=false;renderPluginPage();}}}
  else if(el.dataset.kosellOp)await kosellAction('preview',{orderId:el.dataset.kosellOrder,operation:el.dataset.kosellOp,...(el.dataset.kosellOp==='extend'?{hours:Number(el.closest('.kosell-job').querySelector('[data-kosell-hours]').value)}:{})});
  else if(el.dataset.kosellRemove)await kosellAction('mapping',{lotId:el.dataset.kosellRemove,nodeId:el.dataset.nodeId,remove:true});
});
