/* Account-bound requests; no automatic deletion, refund, or contract acceptance. */
const legalUi={token:'',data:null,admin:null,offset:0,ownOffset:0,loading:false,busy:false,sequence:0,attempt:null};
const legalLabels={access:'Сведения об обработке',export:'Выгрузка данных',correction:'Исправление данных',deletion:'Удаление аккаунта и данных',withdrawal:'Отзыв согласия',incident:'Сообщить об инциденте',claim:'Претензия',refund:'Оплата и возврат'};
const legalStatuses={submitted:'Получено',in_review:'На рассмотрении',answered:'Получен ответ',cancelled:'Закрыто с пояснением'};
const legalEscape=value=>escapeHtml(String(value??''));
const legalDate=value=>{const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString('ru-RU'):'—';};
function resetLegalUi(){legalUi.sequence++;Object.assign(legalUi,{token:'',data:null,admin:null,offset:0,ownOffset:0,loading:false,busy:false,attempt:null});document.querySelector('[data-legal-cabinet]')?.remove();}
function legalRequestMarkup(row,admin=false){
 const id=/^lr_[a-f0-9-]{36}$/.test(row?.id||'')?row.id:'';if(!id||!legalLabels[row.type]||!legalStatuses[row.status])return '';
 return `<article class="legal-request"><header><strong>${legalLabels[row.type]}</strong><span>${legalStatuses[row.status]}</span></header><small>${legalEscape(id)} · ${legalEscape(legalDate(row.createdAt))}${admin?` · аккаунт ${legalEscape(row.userId)}`:''}</small><p>${legalEscape(row.message||'Без дополнительных сведений')}</p>${row.response?`<blockquote><strong>Ответ оператора</strong><br>${legalEscape(row.response)}</blockquote>`:''}${admin&&['submitted','in_review'].includes(row.status)?`<details><summary>Рассмотреть обращение</summary><form data-legal-decision="${id}" data-legal-version="${Number.isSafeInteger(row.version)?row.version:0}"><label>Статус<select name="status"><option value="in_review">На рассмотрении</option><option value="answered">Ответ направлен</option><option value="cancelled">Закрыто с пояснением</option></select></label><label>Ответ пользователю<textarea name="response" maxlength="2000" rows="3" placeholder="Укажите результат и фактически выполненные действия"></textarea></label><p>Статус не выполняет удаление данных или возврат денег. Отвечайте только о действительно выполненных действиях.</p><button class="button button--primary" type="submit">Сохранить ответ</button><div role="status"></div></form></details>`:''}</article>`;
}
function legalCabinetMarkup(){return `<section class="legal-cabinet" data-legal-cabinet><h2>Документы и обращения</h2><p>Оферта и политики подготовлены как проекты. Поддержка и электронные обращения: @zetslaysupport. Обращения из кабинета сохраняются в очереди оператора.</p><nav class="legal-links" aria-label="Юридические документы"><a href="https://t.me/zetslaysupport">Поддержка @zetslaysupport</a><a href="/legal/">Все документы</a><a href="/legal/offer.html">Оферта · проект</a><a href="/legal/privacy.html">Конфиденциальность · проект</a><a href="/legal/refunds.html">Оплата и возвраты · проект</a><a href="/legal/automation-rules.html">Автоматизация · проект</a><a href="/legal/acceptable-use.html">Правила использования · проект</a><button type="button" data-privacy-settings>Настройки cookies</button></nav><form data-legal-request><label>Тема<select name="type">${Object.entries(legalLabels).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label><label>Подробности<textarea name="message" maxlength="2000" rows="3" placeholder="Что нужно проверить или изменить? Для оплаты — номер операции, дата и сумма."></textarea></label><p>Не присылайте Golden Key, пароли, ключи API, данные карты или паспорт. Запрос на удаление и возврат рассматривается оператором; отправка формы не выполняет эти действия автоматически.</p><button class="button button--primary" type="submit">Отправить обращение</button><div role="status" aria-live="polite"></div></form><div class="legal-actions"><button type="button" class="button button--ghost" data-legal-refresh>Обновить обращения</button><button type="button" class="button button--ghost" data-legal-admin hidden>Обращения пользователей</button></div><div data-legal-load-status role="status" aria-live="polite"></div><div data-legal-requests></div><section data-legal-admin-panel hidden><h3>Очередь оператора</h3><p>Получение ответа не означает исполнение запроса. Проверяйте законные сроки и выполняйте необходимые действия отдельно.</p><div data-legal-admin-requests></div><div class="legal-actions"><button type="button" class="button button--ghost" data-legal-admin-prev hidden>Предыдущие</button><button type="button" class="button button--ghost" data-legal-admin-next hidden>Следующие</button></div></section></section>`;}
function renderLegalRequests(){const root=document.querySelector('[data-legal-cabinet]');if(!root)return;
 const own=root.querySelector('[data-legal-requests]');if(own&&legalUi.data){const signature=JSON.stringify([legalUi.data.requests,legalUi.ownOffset,legalUi.data.nextOffset]);if(own.dataset.signature!==signature){own.innerHTML=(legalUi.data.requests.map(r=>legalRequestMarkup(r)).join('')||'<p>Обращений пока нет.</p>')+`<div class="legal-actions">${legalUi.ownOffset>0?'<button type="button" class="button button--ghost" data-legal-own-prev>Предыдущие</button>':''}${legalUi.data.nextOffset!=null?'<button type="button" class="button button--ghost" data-legal-own-next>Следующие</button>':''}</div>`;own.dataset.signature=signature;}}
 const admin=root.querySelector('[data-legal-admin]');if(admin)admin.hidden=legalUi.data?.admin!==true;
 const panel=root.querySelector('[data-legal-admin-panel]');if(panel){panel.hidden=!legalUi.admin||legalUi.data?.admin!==true;if(!panel.hidden){const list=panel.querySelector('[data-legal-admin-requests]'),signature=JSON.stringify(legalUi.admin.requests);if(list.dataset.signature!==signature){list.innerHTML=legalUi.admin.requests.map(r=>legalRequestMarkup(r,true)).join('')||'<p>На этой странице нет обращений.</p>';list.dataset.signature=signature;}panel.querySelector('[data-legal-admin-prev]').hidden=legalUi.offset===0;panel.querySelector('[data-legal-admin-next]').hidden=legalUi.admin.nextOffset===null;}}
}
function mountLegalCabinet(){if(!authState.user||!authState.token)return;if(legalUi.token&&legalUi.token!==authState.token)resetLegalUi();const profile=document.querySelector('[data-profile]');if(!profile||!profile.innerHTML)return;if(!profile.querySelector('[data-legal-cabinet]'))profile.insertAdjacentHTML('beforeend',legalCabinetMarkup());renderLegalRequests();
 const billing=document.querySelector('[data-billing]');if(billing&&!billing.querySelector('[data-billing-legal]'))billing.insertAdjacentHTML('beforeend','<nav class="legal-links" data-billing-legal aria-label="Условия оплаты"><a href="/legal/offer.html">Оферта · проект</a><a href="/legal/refunds.html">Оплата и возвраты · проект</a><a href="/legal/automation-rules.html">Автоматизация · проект</a><a href="/legal/acceptable-use.html">Правила использования · проект</a><a href="/legal/">Реквизиты и документы</a><a href="https://t.me/zetslaysupport">Поддержка @zetslaysupport</a></nav>');
 if(!legalUi.data&&!legalUi.loading)loadLegalRequests();
}
async function loadLegalRequests(admin=false,offset=0){if(!authState.user||legalUi.busy||legalUi.loading)return;const token=authState.token,sequence=++legalUi.sequence;legalUi.token=token;legalUi.loading=true;const status=document.querySelector('[data-legal-load-status]');if(status)status.textContent='Загружаем обращения…';
 try{const result=await apiRequest(admin?`/api/v1/admin/legal/requests?offset=${offset}`:`/api/v1/legal/requests?offset=${offset}`,{authenticated:true});if(token!==authState.token||sequence!==legalUi.sequence)return;if(admin){legalUi.admin=result;legalUi.offset=offset;}else{legalUi.data=result;legalUi.ownOffset=offset;}renderLegalRequests();if(status?.isConnected)status.textContent='';}
 catch(e){if(token===authState.token&&sequence===legalUi.sequence&&status?.isConnected)status.textContent=humanError(e);}
 finally{if(token===authState.token&&sequence===legalUi.sequence)legalUi.loading=false;}
}
async function submitLegalRequest(form,decision=false){if(legalUi.busy||legalUi.loading||!authState.user||!form.reportValidity())return;const token=authState.token,sequence=++legalUi.sequence;legalUi.token=token;legalUi.busy=true;
 const data=new FormData(form),status=form.querySelector('[role=status]'),buttons=[...form.querySelectorAll('button,select,textarea')];buttons.forEach(b=>b.disabled=true);
 const content=decision?{status:data.get('status'),response:data.get('response'),version:Number(form.dataset.legalVersion)}:{type:data.get('type'),message:data.get('message')||''};
 if(!decision){const signature=JSON.stringify(content);if(legalUi.attempt?.signature!==signature)legalUi.attempt={signature,key:crypto.randomUUID()};content.requestKey=legalUi.attempt.key;}
 try{const result=await apiRequest(decision?`/api/v1/admin/legal/requests/${form.dataset.legalDecision}`:'/api/v1/legal/requests',{method:'POST',authenticated:true,body:content});if(token!==authState.token||sequence!==legalUi.sequence)return;
  if(!decision){form.reset();legalUi.attempt=null;status.textContent=`Обращение сохранено: ${result.id}. Ответ появится здесь. Это не подтверждение удаления данных или возврата.`;legalUi.data??={requests:[],admin:false};legalUi.data.requests=[result,...legalUi.data.requests.filter(r=>r.id!==result.id)];}
  else{legalUi.admin.requests=legalUi.admin.requests.map(r=>r.id===result.id?{...r,...result}:r);if(legalUi.data)legalUi.data.requests=legalUi.data.requests.map(r=>r.id===result.id?result:r);}
  renderLegalRequests();
 }catch(e){if(token===authState.token&&sequence===legalUi.sequence&&status?.isConnected)status.textContent=humanError(e);}
 finally{if(token===authState.token&&sequence===legalUi.sequence){legalUi.busy=false;buttons.forEach(b=>b.disabled=false);}}
}
function bootstrapLegalCabinet(){if(typeof renderProfile==='function'){const prior=renderProfile;renderProfile=function(...args){const token=authState.token,existing=legalUi.token===token?document.querySelector('[data-legal-cabinet]'):null;const result=prior.apply(this,args),profile=document.querySelector('[data-profile]');if(existing&&authState.user&&token===authState.token&&profile?.innerHTML&&!profile.contains(existing))profile.appendChild(existing);mountLegalCabinet();return result;};}if(typeof resetAccountData==='function'){const prior=resetAccountData;resetAccountData=function(...args){resetLegalUi();return prior.apply(this,args);};}
 document.addEventListener('submit',e=>{if(e.target.matches?.('[data-legal-request],[data-legal-decision]')){e.preventDefault();submitLegalRequest(e.target,e.target.hasAttribute('data-legal-decision'));}});
 document.addEventListener('click',e=>{if(e.target.closest?.('[data-legal-refresh]'))loadLegalRequests();if(e.target.closest?.('[data-legal-own-prev]'))loadLegalRequests(false,Math.max(0,legalUi.ownOffset-50));if(e.target.closest?.('[data-legal-own-next]')&&legalUi.data?.nextOffset!=null)loadLegalRequests(false,legalUi.data.nextOffset);if(e.target.closest?.('[data-legal-admin]'))loadLegalRequests(true,0);if(e.target.closest?.('[data-legal-admin-prev]'))loadLegalRequests(true,Math.max(0,legalUi.offset-50));if(e.target.closest?.('[data-legal-admin-next]')&&legalUi.admin?.nextOffset!=null)loadLegalRequests(true,legalUi.admin.nextOffset);});
 mountLegalCabinet();}
bootstrapLegalCabinet();
