import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('./legal-cabinet.js',import.meta.url),'utf8'),privacy=readFileSync(new URL('../legal/privacy-controls.js',import.meta.url),'utf8');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cabinet(){const c=vm.createContext({document:{querySelector:()=>null,addEventListener(){}},authState:{token:'fixture',user:{}},escapeHtml:escape,humanError:e=>e.message,Date,crypto:{randomUUID:()=> '12345678-1234-1234-1234-123456789abc'},console});vm.runInContext(source,c);return {c,run:s=>vm.runInContext(s,c)};}
const row={id:'lr_12345678-1234-1234-1234-123456789abc',type:'deletion',status:'submitted',message:'<img src=x onerror=alert(1)>',response:'<script>unsafe</script>',version:0,createdAt:'2026-10-07T00:00:00Z'};
test('request presentation escapes user and operator content and keeps admin controls private',()=>{const f=cabinet();f.c.row=row;const html=f.run('legalRequestMarkup(row)');assert.match(html,/&lt;img/);assert.match(html,/&lt;script/);assert.doesNotMatch(html,/<img|<script|data-legal-decision/);assert.match(f.run('legalRequestMarkup(row,true)'),/data-legal-decision/);assert.match(f.run('legalCabinetMarkup()'),/data-legal-admin hidden/);assert.match(f.run('legalCabinetMarkup()'),/не выполняет эти действия автоматически/);});
test('late legal requests cannot replace another account or expose the previous admin inbox',async()=>{const f=cabinet();let resolve;f.c.apiRequest=()=>new Promise(r=>resolve=r);const promise=f.run('loadLegalRequests()');f.run("authState.token='other';resetLegalUi()");resolve({admin:true,requests:[row]});await promise;assert.equal(f.run('legalUi.data'),null);assert.equal(f.run('legalUi.admin'),null);assert.equal(f.run('legalUi.loading'),false);});
test('a lost submit response retains draft and idempotency key, double click performs one request',async()=>{const f=cabinet();let reject,calls=[];f.c.apiRequest=(path,options)=>{calls.push({path,options});return new Promise((_,r)=>reject=r);};const status={textContent:'',isConnected:true},button={disabled:false};let resets=0;f.c.FormData=class{get(k){return k==='type'?'deletion':'draft text';}};f.c.form={reportValidity:()=>true,querySelector:()=>status,querySelectorAll:()=>[button],reset:()=>resets++};const pending=f.run('submitLegalRequest(form)');await f.run('submitLegalRequest(form)');assert.equal(calls.length,1);assert.equal(calls[0].options.authenticated,true);reject(Error('Connection interrupted'));await pending;assert.equal(resets,0);assert.equal(button.disabled,false);assert.equal(f.run('legalUi.attempt.key'),calls[0].options.body.requestKey);assert.equal(status.textContent,'Connection interrupted');});
test('terminal request cannot offer administrative changes and invalid ids never become routes',()=>{const f=cabinet();f.c.row={...row,status:'answered'};assert.doesNotMatch(f.run('legalRequestMarkup(row,true)'),/data-legal-decision/);f.c.row={...row,id:'../../admin'};assert.equal(f.run('legalRequestMarkup(row,true)'),'');});
test('background profile redraw preserves the request draft only for the same authenticated account',()=>{
 const panel={draft:'UNSENT_PRIVATE_TEXT',querySelector:()=>null},profile={innerHTML:'PROFILE',child:panel,querySelector(){return this.child;},contains(p){return this.child===p;},appendChild(p){this.child=p;},insertAdjacentHTML(){this.child={draft:'',querySelector:()=>null};}};
 const document={querySelector:s=>s==='[data-profile]'?profile:s==='[data-legal-cabinet]'?profile.child:null,addEventListener(){}};
 const authState={token:'a',user:null};const c=vm.createContext({document,authState,escapeHtml:escape,humanError:e=>e.message,Date,renderProfile(){profile.innerHTML='REDRAWN';profile.child=null;}});vm.runInContext(source,c);
 vm.runInContext("authState.user={};legalUi.token='a';legalUi.data={requests:[],admin:false};renderProfile()",c);assert.equal(profile.child,panel);assert.equal(profile.child.draft,'UNSENT_PRIVATE_TEXT');
 authState.token='b';vm.runInContext('renderProfile()',c);assert.notEqual(profile.child,panel);assert.notEqual(profile.child?.draft,'UNSENT_PRIVATE_TEXT');
});
function preferences(storage=new Map()){const w={},c=vm.createContext({window:w,document:{addEventListener(){}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},Date});vm.runInContext(privacy,c);return w.ZetSlayPrivacy;}
test('privacy defaults are necessary-only, cannot enable optional trackers and expire with version',()=>{const s=new Map(),p=preferences(s);assert.equal(p.read(),null);assert.equal(p.saveNecessary(),true);assert.equal(p.read().optional,false);assert.equal(p.read().necessary,true);const raw=JSON.parse([...s.values()][0]);assert.deepEqual(Object.keys(raw).sort(),['at','necessary','optional','version']);raw.optional=true;s.set('zetslay_privacy_preferences',JSON.stringify(raw));assert.equal(p.read(),null);raw.optional=false;raw.at-=181*86400000;s.set('zetslay_privacy_preferences',JSON.stringify(raw));assert.equal(p.read(),null);p.reset();assert.equal(s.size,0);});
test('blocked browser storage is handled without accepting optional resources',()=>{const w={},c=vm.createContext({window:w,document:{addEventListener(){}},localStorage:{getItem(){throw Error();},setItem(){throw Error();},removeItem(){throw Error();}},Date});vm.runInContext(privacy,c);assert.equal(w.ZetSlayPrivacy.read(),null);assert.equal(w.ZetSlayPrivacy.saveNecessary(),false);assert.equal(w.ZetSlayPrivacy.reset(),false);});
test('legal links, local fonts and script ordering are present without adding consent to login or payments',()=>{const root=readFileSync(new URL('../index.html',import.meta.url),'utf8'),app=readFileSync(new URL('./index.html',import.meta.url),'utf8');for(const text of [root,app]){assert.match(text,/assets\/fonts\/fonts.css/);assert.doesNotMatch(text,/fonts.googleapis.com|fonts.gstatic.com/);assert.match(text,/privacy-controls.js/);}assert.match(root,/data-legal-links/);assert.match(app,/data-auth-legal-links/);assert.ok(app.indexOf('legal-cabinet.js')>app.indexOf('src="app.js'));assert.match(app,/Секреты FunPay/);assert.doesNotMatch(app,/name="(?:legalAccepted|marketingConsent)"/);});
