import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('./steam-rent.js',import.meta.url),'utf8');
const snapshot={config:{automatic:false,buyerBlacklist:[],deliveryTemplate:'hello'},accounts:[],mappings:[],orders:[],logs:[],analytics:{active:0,waiting:0,attention:0,revenueMinor:{RUB:0,USD:0},refundMinor:{RUB:0,USD:0},games:[]}};
function harness(api=async()=>snapshot){const calls=[],events=new Map();let resets=0;const context=vm.createContext({Date,Intl,JSON,Array,Object,Promise,queueMicrotask,authState:{token:'one',user:{id:'u'},workspace:{plan:{id:'legendary',active:true}}},sessionGeneration:1,document:{addEventListener:(t,f)=>events.set(t,f),querySelector:()=>null},escapeHtml:v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),apiRequest:async(p,o)=>{calls.push([p,o]);return api(p,o)},humanError:e=>e.message,renderPluginPage(){},resetAccountData(){resets++},pluginPurchaseModel:()=>({amount:0,price:'Бесплатно'}),FormData:class{constructor(form){this.form=form}get(k){return this.form.data[k]??''}getAll(k){return this.form.data[k]||[]}has(k){return Boolean(this.form.data[k])}}});const run=s=>vm.runInContext(s,context);run(source);return {run,calls,events,context,async ready(){for(let i=0;i<12;i++)await Promise.resolve()},get resets(){return resets}};}
test('only installed paid users see management; trial shows upgrade without requests',async()=>{const h=harness();assert.equal(h.run('steamRentMarkup({installed:false})'),'');h.context.authState.workspace.plan.id='trial_3d';assert.match(h.run('steamRentMarkup({installed:true})'),/не входят в пробный/);await h.ready();assert.equal(h.calls.length,0);});
test('status read and all actions explicitly authenticate through existing apiRequest contract',async()=>{const h=harness();h.run('steamRentMarkup({installed:true})');await h.ready();assert.equal(h.calls[0][1].authenticated,true);await h.run("steamRentRequest('settings',{config:{automatic:false}})");assert.equal(h.calls.at(-1)[1].authenticated,true);assert.equal(h.calls.at(-1)[1].method,'POST');});
test('overlapping click sends one POST and late results cannot update a different session',async()=>{let finish;const h=harness(()=>new Promise(r=>finish=r));h.run("steamRentRequest('settings',{});steamRentRequest('settings',{})");assert.equal(h.calls.length,1);h.run("authState.token='two';sessionGeneration++;resetAccountData()");finish(snapshot);await h.ready();assert.equal(h.run('steamRentUi.status'),null);assert.equal(h.resets,1);});
test('account reset clears sensitive Guard result and pending confirmation',()=>{const h=harness();h.run("steamRentUi.report={kind:'guard',result:{code:'SECRET'}};steamRentUi.plan={token:'nonce'};resetAccountData()");assert.equal(h.run('steamRentUi.report'),null);assert.equal(h.run('steamRentUi.plan'),null);});
test('uploaded file completing after logout cannot be submitted using the next account',async()=>{let finish;const h=harness();const form={dataset:{srForm:'account'},data:{label:'A',game:'G',maFileUpload:{size:12,text:()=>new Promise(r=>finish=r)}},closest(){return this}};const promise=h.events.get('submit')({target:form,preventDefault(){}});h.run("authState.token='two';sessionGeneration++;resetAccountData()");finish('sensitive');await promise;assert.equal(h.calls.length,0);});
test('API errors are visible, retries retain known state and do not claim successful saving',async()=>{const h=harness(async()=>{throw Error('Steam rejected')});h.run('steamRentMarkup({installed:true})');await h.ready();assert.match(h.run('steamRentMarkup({installed:true})'),/Steam rejected/);assert.match(h.run('steamRentMarkup({installed:true})'),/data-sr-refresh/);});
test('metadata and confirmation titles are escaped and secret inputs never prefill',()=>{const h=harness();h.context.data={...snapshot,accounts:[{id:'id',label:'<script>X</script>',game:'Game',mode:'online'}],config:{...snapshot.config,deliveryTemplate:'<svg/onload=x>'}};h.run('resetSteamRentUi();steamRentUi.status=data');const html=h.run('steamRentMarkup({installed:true})');assert.ok(!html.includes('<script>X'));assert.match(html,/&lt;script&gt;/);assert.match(html,/type="password"/);assert.match(html,/maFileUpload/);assert.match(html,/data-sr-form="mapping"/);assert.match(html,/data-sr-period="today"/);});
test('new module has a legendary palette, page hook and no generated banner asset',()=>{const page=readFileSync(new URL('./plugin-page.js',import.meta.url),'utf8'),rarity=readFileSync(new URL('./plugin-rarity.js',import.meta.url),'utf8'),html=readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.match(page,/steamRentMarkup/);assert.match(rarity,/'zetslay.steam-rent':\s*'legendary'/);assert.match(html,/steam-rent.js/);assert.match(html,/steam-rent.css/);assert.doesNotMatch(source,/<img|data:image/);});
test('zero seeded catalogue price is labelled unspecified, with administrator prices preserved',()=>{const h=harness();assert.equal(h.run("pluginPurchaseModel({id:'zetslay.steam-rent'}).amount"),null);assert.equal(h.run("pluginPurchaseModel({id:'other'}).amount"),0);});
